/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class AG_BloodAltarAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new AG_BloodAltarAddonDeed();
			}
		}

		[ Constructable ]
		public AG_BloodAltarAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 4624 );
			ac.Hue = 1908;
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 4626 );
			ac.Hue = 1908;
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 4627 );
			ac.Hue = 1908;
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 4628 );
			ac.Hue = 1908;
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 4629 );
			ac.Hue = 1908;
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 4630 );
			ac.Hue = 1908;
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 4622 );
			ac.Hue = 1908;
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 6571 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 0, 0, 4 );
			ac = new AddonComponent( 6882 );
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 6883 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 6884 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 6880 );
			AddComponent( ac, 0, 0, 8 );
			ac = new AddonComponent( 4650 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 4625 );
			ac.Hue = 1908;
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 4650 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 4650 );
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 4650 );
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 4650 );
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 4623 );
			ac.Hue = 1908;
			AddComponent( ac, 0, -1, 0 );

		}

		public AG_BloodAltarAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class AG_BloodAltarAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new AG_BloodAltarAddon();
			}
		}

		[Constructable]
		public AG_BloodAltarAddonDeed()
		{
			Name = "AG_BloodAltar";
		}

		public AG_BloodAltarAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}