/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class SerenityWallEastAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new SerenityWallEastAddonDeed();
			}
		}

		[ Constructable ]
		public SerenityWallEastAddon()
		{
			AddComponent( new AddonComponent( 2835 ), 1, 0, 0 );
			AddComponent( new AddonComponent( 2833 ), 1, 1, 0 );
			AddComponent( new AddonComponent( 6039 ), 1, 1, 9 );
			AddComponent( new AddonComponent( 13451 ), 1, 1, 9 );
			AddComponent( new AddonComponent( 2834 ), 0, 1, 0 );
			AddComponent( new AddonComponent( 13561 ), 0, 1, 9 );
			AddComponent( new AddonComponent( 926 ), 0, 1, 19 );

		}

		public SerenityWallEastAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class SerenityWallEastAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new SerenityWallEastAddon();
			}
		}

		[Constructable]
		public SerenityWallEastAddonDeed()
		{
			Name = "SerenityWallEast";
		}

		public SerenityWallEastAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}