/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class CanopyBedBlue2Addon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new CanopyBedBlue2AddonDeed();
			}
		}

		[ Constructable ]
		public CanopyBedBlue2Addon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 298 );
			ac.Name = "Canopy";
			AddComponent( ac, -2, 2, 0 );
			ac = new AddonComponent( 298 );
			ac.Name = "Canopy";
			AddComponent( ac, -2, -2, 0 );
			ac = new AddonComponent( 298 );
			AddComponent( ac, 2, 2, 0 );
			ac = new AddonComponent( 298 );
			ac.Name = "Canopy";
			AddComponent( ac, 2, -2, 0 );
			ac = new AddonComponent( 323 );
			ac.Name = "Canopy";
			AddComponent( ac, -2, -1, 17 );
			ac = new AddonComponent( 323 );
			ac.Name = "Canopy";
			AddComponent( ac, -2, 0, 17 );
			ac = new AddonComponent( 323 );
			ac.Name = "Canopy";
			AddComponent( ac, -2, 1, 17 );
			ac = new AddonComponent( 323 );
			ac.Name = "Canopy";
			AddComponent( ac, -2, 2, 17 );
			ac = new AddonComponent( 323 );
			ac.Name = "Canopy";
			AddComponent( ac, 2, -1, 17 );
			ac = new AddonComponent( 323 );
			ac.Name = "Canopy";
			AddComponent( ac, 2, 0, 17 );
			ac = new AddonComponent( 323 );
			ac.Name = "Canopy";
			AddComponent( ac, 2, 1, 17 );
			ac = new AddonComponent( 323 );
			ac.Name = "Canopy";
			AddComponent( ac, 2, 2, 17 );
			ac = new AddonComponent( 322 );
			ac.Name = "Canopy";
			AddComponent( ac, -1, 2, 17 );
			ac = new AddonComponent( 322 );
			ac.Name = "Canopy";
			AddComponent( ac, 0, 2, 17 );
			ac = new AddonComponent( 322 );
			ac.Name = "Canopy";
			AddComponent( ac, 1, 2, 17 );
			ac = new AddonComponent( 322 );
			ac.Name = "Canopy";
			AddComponent( ac, 2, 2, 17 );
			ac = new AddonComponent( 322 );
			ac.Name = "Canopy";
			AddComponent( ac, -1, -2, 17 );
			ac = new AddonComponent( 322 );
			ac.Name = "Canopy";
			AddComponent( ac, 0, -2, 17 );
			ac = new AddonComponent( 322 );
			ac.Name = "Canopy";
			AddComponent( ac, 1, -2, 17 );
			ac = new AddonComponent( 322 );
			ac.Name = "Canopy";
			AddComponent( ac, 2, -2, 17 );
			ac = new AddonComponent( 10383 );
			AddComponent( ac, -2, -1, 0 );
			ac = new AddonComponent( 10383 );
			AddComponent( ac, -2, 0, 0 );
			ac = new AddonComponent( 10383 );
			AddComponent( ac, -2, 1, 0 );
			ac = new AddonComponent( 2682 );
			ac.Hue = 594;
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 2683 );
			ac.Hue = 594;
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 2681 );
			ac.Hue = 594;
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 2680 );
			ac.Hue = 594;
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 2750 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 2750 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 2750 );
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 2750 );
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 2750 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 2750 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 2750 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 2750 );
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 2750 );
			AddComponent( ac, -1, 2, 0 );
			ac = new AddonComponent( 2750 );
			AddComponent( ac, 0, 2, 0 );
			ac = new AddonComponent( 2750 );
			AddComponent( ac, 1, 2, 0 );
			ac = new AddonComponent( 2807 );
			AddComponent( ac, -1, -2, 0 );
			ac = new AddonComponent( 2807 );
			AddComponent( ac, 0, -2, 0 );
			ac = new AddonComponent( 2807 );
			AddComponent( ac, 1, -2, 0 );
			ac = new AddonComponent( 2808 );
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 2808 );
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 2808 );
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 2808 );
			AddComponent( ac, 2, 2, 0 );
			ac = new AddonComponent( 2809 );
			AddComponent( ac, -1, 3, 0 );
			ac = new AddonComponent( 2809 );
			AddComponent( ac, 0, 3, 0 );
			ac = new AddonComponent( 2809 );
			AddComponent( ac, 1, 3, 0 );
			ac = new AddonComponent( 2757 );
			AddComponent( ac, 2, -2, 0 );
			ac = new AddonComponent( 2754 );
			AddComponent( ac, 2, 3, 0 );
			ac = new AddonComponent( 10383 );
			AddComponent( ac, -2, 2, 0 );
			ac = new AddonComponent( 7807 );
			ac.Name = "nightstand";
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 2842 );
			ac.Light = LightType.Circle225;
			ac.Name = "lamp";
			AddComponent( ac, -1, -1, 8 );
			ac = new AddonComponent( 2330 );
			ac.Hue = 594;
			ac.Name = "lamp shade";
			AddComponent( ac, -1, -1, 10 );
			ac = new AddonComponent( 5645 );
			ac.Hue = 594;
			AddComponent( ac, -1, 2, 0 );
			ac = new AddonComponent( 5645 );
			ac.Hue = 594;
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 5645 );
			ac.Hue = 594;
			AddComponent( ac, 3, 2, 0 );
			ac = new AddonComponent( 5645 );
			ac.Hue = 594;
			AddComponent( ac, 3, -1, 0 );
			ac = new AddonComponent( 5646 );
			ac.Hue = 594;
			AddComponent( ac, -1, 3, 0 );
			ac = new AddonComponent( 5646 );
			ac.Hue = 594;
			AddComponent( ac, 2, 3, 0 );
			ac = new AddonComponent( 5646 );
			ac.Hue = 594;
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 5646 );
			ac.Hue = 594;
			AddComponent( ac, -1, -1, 0 );

		}

		public CanopyBedBlue2Addon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class CanopyBedBlue2AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new CanopyBedBlue2Addon();
			}
		}

		[Constructable]
		public CanopyBedBlue2AddonDeed()
		{
			Name = "CanopyBedBlue2";
		}

		public CanopyBedBlue2AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}