/////////////////////////////////////
//**Generated by Ryan**//
/////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
    public class LegsoftheForsaken : PlateLegs, ITokunoDyable
	{
	 	public override int ArtifactRarity{ get{ return 10; } }
	 	public override int InitMinHits{ get{ return 255; } }
	 	public override int InitMaxHits{ get{ return 255; } }

	 	[Constructable]
	 	public LegsoftheForsaken()
	 	{
	 	 	Name = "Legs of the Forsaken";
	 	 	Hue = 1418;
	 	 	ArmorAttributes.MageArmor = 1;
            ArmorAttributes.SelfRepair = 3;
            PhysicalBonus = 10;
            PoisonBonus = 10;
            EnergyBonus = 10;
            ColdBonus = 10;
			FireBonus = 10;
			Attributes.DefendChance = 5;
			Attributes.Luck = 100;
			Attributes.NightSight = 1;
			Attributes.ReflectPhysical = 10;
			Attributes.RegenHits = 2;
			Attributes.RegenMana = 2;
			Attributes.SpellDamage = 5;
			Attributes.WeaponDamage = 5;
			Attributes.WeaponSpeed = 5;
	 	}

	 	public LegsoftheForsaken(Serial serial) : base( serial )
	 	{
	 	}
	 	public override void Serialize( GenericWriter writer )
	 	{
	 	 	base.Serialize( writer );

	 	 	writer.Write( (int) 0 );
	 	}
	 	public override void Deserialize(GenericReader reader)
	 	{
	 	 	base.Deserialize( reader );

	 	 	int version = reader.ReadInt();
	 	}
	}
}
