/////////////////////////////////////
//**Generated by Ryan**//
/////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
    public class ArmsoftheForsaken : PlateArms, ITokunoDyable
	{
	 	public override int ArtifactRarity{ get{ return 10; } }
	 	public override int InitMinHits{ get{ return 255; } }
	 	public override int InitMaxHits{ get{ return 255; } }

	 	[Constructable]
	 	public ArmsoftheForsaken()
	 	{
	 	 	Name = "Arms of the Forsaken";
	 	 	Hue = 1418;
	 	 	ArmorAttributes.MageArmor = 1;
	 	 	ArmorAttributes.SelfRepair = 3;
            PhysicalBonus = 10;
            FireBonus = 10;
            EnergyBonus = 10;
            ColdBonus = 10;
            PoisonBonus = 10;
            Attributes.BonusDex = 5;
		    Attributes.DefendChance = 15;
			Attributes.Luck = 100;
			Attributes.NightSight = 1;
            Attributes.ReflectPhysical = 10;
			Attributes.SpellDamage = 10;
			Attributes.WeaponDamage = 10;
			Attributes.WeaponSpeed = 10;
	 	}

	 	public ArmsoftheForsaken(Serial serial) : base( serial )
	 	{
	 	}
	 	public override void Serialize( GenericWriter writer )
	 	{
	 	 	base.Serialize( writer );

	 	 	writer.Write( (int) 0 );
	 	}
	 	public override void Deserialize(GenericReader reader)
	 	{
	 	 	base.Deserialize( reader );

	 	 	int version = reader.ReadInt();
	 	}
	}
}
