/////////////////////////////////////
//**Generated by Ryans Scripts**//
/////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
    public class ForsakenRobe : Robe, ITokunoDyable
	{
	 	public override int ArtifactRarity{ get{ return 10; } }
	 	//public  int InitMinHits{ get{ return 100; } }
	 	//public  int InitMaxHits{ get{ return 100; } }

	 	[Constructable]
	 	public ForsakenRobe()
	 	{
	 	 	Name = "Forsaken Robe";
	 	 	Hue = 1418;
			Attributes.AttackChance = 5;
			Attributes.BonusHits = 10;
			Attributes.BonusInt = 5;
			Attributes.BonusMana = 5;
			Attributes.BonusStam = 10;
			Attributes.CastRecovery = 3;
			Attributes.CastSpeed = 1;
			Attributes.DefendChance = 5;
			Attributes.Luck = 150;
			Attributes.NightSight = 1;
			Attributes.ReflectPhysical = 5;

	 	}

	 	public ForsakenRobe(Serial serial) : base( serial )
	 	{
	 	}
	 	public override void Serialize( GenericWriter writer )
	 	{
	 	 	base.Serialize( writer );

	 	 	writer.Write( (int) 0 );
	 	}
	 	public override void Deserialize(GenericReader reader)
	 	{
	 	 	base.Deserialize( reader );

	 	 	int version = reader.ReadInt();
	 	}

        public override void OnDoubleClick(Mobile from)
        {

            Item u = from.Backpack.FindItemByType(typeof(ForsakenRobe));
            if (u != null)
            {

                if (this.ItemID == 12218) this.ItemID = 12217;
                else if (this.ItemID == 12217) this.ItemID = 7939;
                else if (this.ItemID == 7939) this.ItemID = 9860;
                else if (this.ItemID == 9860) this.ItemID = 12218;


            }
            else
            {
                from.SendMessage("You must have the item in your pack to morph it.");
            }

        }
    }
}

