/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class AG_FriendshipLampFemaleAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new AG_FriendshipLampFemaleAddonDeed();
			}
		}

		[ Constructable ]
		public AG_FriendshipLampFemaleAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 4644 );
			ac.Hue = 1150;
			AddComponent( ac, 0, 1, 6 );
			ac = new AddonComponent( 5018 );
			ac.Hue = 1150;
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 7110 );
			AddComponent( ac, 0, 0, 6 );
			ac = new AddonComponent( 2581 );
			ac.Light = LightType.Circle225;
			AddComponent( ac, 0, 1, 6 );
			ac = new AddonComponent( 2586 );
			ac.Light = LightType.ArchedWindowEast;
			ac.Hue = 1150;
			AddComponent( ac, 1, 1, 4 );
			ac = new AddonComponent( 7111 );
			AddComponent( ac, -1, 0, 1 );

		}

		public AG_FriendshipLampFemaleAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class AG_FriendshipLampFemaleAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new AG_FriendshipLampFemaleAddon();
			}
		}

		[Constructable]
		public AG_FriendshipLampFemaleAddonDeed()
		{
			Name = "AG_FriendshipLampFemale";
		}

		public AG_FriendshipLampFemaleAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}