/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class AG_redrosevaseAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new AG_redrosevaseAddonDeed();
			}
		}

		[ Constructable ]
		public AG_redrosevaseAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 3152 );
			AddComponent( ac, 0, 0, 4 );
			ac = new AddonComponent( 3151 );
			AddComponent( ac, 0, 0, 1 );
			ac = new AddonComponent( 3152 );
			AddComponent( ac, 0, 1, 9 );
			ac = new AddonComponent( 6378 );
			ac.Name = "Whispering Rose";
			AddComponent( ac, 0, 0, 16 );
			ac = new AddonComponent( 2885 );
			ac.Hue = 1150;
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 3151 );
			AddComponent( ac, 0, 0, 4 );
			ac = new AddonComponent( 3234 );
			AddComponent( ac, 0, 0, 3 );

		}

		public AG_redrosevaseAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class AG_redrosevaseAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new AG_redrosevaseAddon();
			}
		}

		[Constructable]
		public AG_redrosevaseAddonDeed()
		{
			Name = "AG_redrosevase";
		}

		public AG_redrosevaseAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}