/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class AG_santasleighsouthAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new AG_santasleighsouthAddonDeed();
			}
		}

		[ Constructable ]
		public AG_santasleighsouthAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 6077 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 6077 );
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 6090 );
			AddComponent( ac, -2, -2, 0 );
			ac = new AddonComponent( 6077 );
			AddComponent( ac, 0, -4, 0 );
			ac = new AddonComponent( 6077 );
			AddComponent( ac, -1, -3, 0 );
			ac = new AddonComponent( 14973 );
			AddComponent( ac, 1, -4, 0 );
			ac = new AddonComponent( 6086 );
			AddComponent( ac, 2, -5, 0 );
			ac = new AddonComponent( 6077 );
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 6077 );
			AddComponent( ac, -1, -2, 0 );
			ac = new AddonComponent( 6092 );
			AddComponent( ac, 2, -2, 0 );
			ac = new AddonComponent( 6077 );
			AddComponent( ac, 0, -5, 0 );
			ac = new AddonComponent( 3272 );
			AddComponent( ac, -1, -4, 0 );
			ac = new AddonComponent( 6077 );
			AddComponent( ac, -1, -4, 0 );
			ac = new AddonComponent( 6085 );
			AddComponent( ac, -2, -6, 0 );
			ac = new AddonComponent( 6086 );
			AddComponent( ac, 1, -6, 0 );
			ac = new AddonComponent( 6092 );
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 6077 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 6077 );
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 14974 );
			AddComponent( ac, 1, -5, 0 );
			ac = new AddonComponent( 14933 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 6077 );
			AddComponent( ac, -1, -5, 0 );
			ac = new AddonComponent( 14933 );
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 6091 );
			AddComponent( ac, 0, -6, 0 );
			ac = new AddonComponent( 6077 );
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 6077 );
			AddComponent( ac, 1, -3, 0 );
			ac = new AddonComponent( 6090 );
			AddComponent( ac, -2, -3, 0 );
			ac = new AddonComponent( 6077 );
			AddComponent( ac, 1, -2, 0 );
			ac = new AddonComponent( 6091 );
			AddComponent( ac, -1, -6, 0 );
			ac = new AddonComponent( 14933 );
			AddComponent( ac, 1, -2, 0 );
			ac = new AddonComponent( 6090 );
			AddComponent( ac, -2, -1, 0 );
			ac = new AddonComponent( 6092 );
			AddComponent( ac, 2, -3, 0 );
			ac = new AddonComponent( 6090 );
			AddComponent( ac, -2, -4, 0 );
			ac = new AddonComponent( 6090 );
			AddComponent( ac, -2, -5, 0 );
			ac = new AddonComponent( 6077 );
			AddComponent( ac, 0, -3, 0 );
			ac = new AddonComponent( 6092 );
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 6077 );
			AddComponent( ac, 0, -2, 0 );
			ac = new AddonComponent( 6092 );
			AddComponent( ac, 2, -4, 0 );
			ac = new AddonComponent( 6084 );
			AddComponent( ac, 1, -5, 0 );
			ac = new AddonComponent( 6090 );
			AddComponent( ac, -2, 0, 0 );
			ac = new AddonComponent( 6077 );
			AddComponent( ac, 1, -4, 0 );
			ac = new AddonComponent( 6077 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 6089 );
			AddComponent( ac, 1, 6, 0 );
			ac = new AddonComponent( 6077 );
			AddComponent( ac, 0, 4, 0 );
			ac = new AddonComponent( 6077 );
			AddComponent( ac, -1, 4, 0 );
			ac = new AddonComponent( 14933 );
			AddComponent( ac, 1, 3, 0 );
			ac = new AddonComponent( 6077 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 6092 );
			AddComponent( ac, 2, 5, 0 );
			ac = new AddonComponent( 6077 );
			AddComponent( ac, 0, 3, 0 );
			ac = new AddonComponent( 6089 );
			AddComponent( ac, -1, 6, 0 );
			ac = new AddonComponent( 6077 );
			AddComponent( ac, 1, 4, 0 );
			ac = new AddonComponent( 6092 );
			AddComponent( ac, 2, 3, 0 );
			ac = new AddonComponent( 6090 );
			AddComponent( ac, -2, 5, 0 );
			ac = new AddonComponent( 6090 );
			AddComponent( ac, -2, 3, 0 );
			ac = new AddonComponent( 6090 );
			AddComponent( ac, -2, 1, 0 );
			ac = new AddonComponent( 14933 );
			AddComponent( ac, 1, 4, 0 );
			ac = new AddonComponent( 14933 );
			AddComponent( ac, 1, 2, 0 );
			ac = new AddonComponent( 6090 );
			AddComponent( ac, -2, 2, 0 );
			ac = new AddonComponent( 6089 );
			AddComponent( ac, 0, 6, 0 );
			ac = new AddonComponent( 6077 );
			AddComponent( ac, -1, 5, 0 );
			ac = new AddonComponent( 14933 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 6077 );
			AddComponent( ac, 1, 3, 0 );
			ac = new AddonComponent( 6077 );
			AddComponent( ac, 1, 2, 0 );
			ac = new AddonComponent( 6092 );
			AddComponent( ac, 2, 2, 0 );
			ac = new AddonComponent( 6077 );
			AddComponent( ac, -1, 2, 0 );
			ac = new AddonComponent( 6077 );
			AddComponent( ac, -1, 3, 0 );
			ac = new AddonComponent( 6077 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 6088 );
			AddComponent( ac, -2, 6, 0 );
			ac = new AddonComponent( 14935 );
			AddComponent( ac, 1, 6, 2 );
			ac = new AddonComponent( 6077 );
			AddComponent( ac, 0, 2, 0 );
			ac = new AddonComponent( 14933 );
			AddComponent( ac, 1, 5, 0 );
			ac = new AddonComponent( 6077 );
			AddComponent( ac, 0, 5, 0 );
			ac = new AddonComponent( 6090 );
			AddComponent( ac, -2, 4, 0 );
			ac = new AddonComponent( 6092 );
			AddComponent( ac, 2, 4, 0 );
			ac = new AddonComponent( 6087 );
			AddComponent( ac, 2, 6, 0 );
			ac = new AddonComponent( 6092 );
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 6077 );
			AddComponent( ac, 1, 5, 0 );

		}

		public AG_santasleighsouthAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class AG_santasleighsouthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new AG_santasleighsouthAddon();
			}
		}

		[Constructable]
		public AG_santasleighsouthAddonDeed()
		{
			Name = "AG_santasleighsouth";
		}

		public AG_santasleighsouthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}