/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class AG_windowboxeast3Addon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new AG_windowboxeast3AddonDeed();
			}
		}

		[ Constructable ]
		public AG_windowboxeast3Addon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 2825 );
			ac.Name = "windowbox";
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 3203 );
			AddComponent( ac, 0, 0, 2 );
			ac = new AddonComponent( 3237 );
			AddComponent( ac, 0, 0, 6 );

		}

		public AG_windowboxeast3Addon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class AG_windowboxeast3AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new AG_windowboxeast3Addon();
			}
		}

		[Constructable]
		public AG_windowboxeast3AddonDeed()
		{
			Name = "AG_windowboxeast3";
		}

		public AG_windowboxeast3AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}