/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class AG_BloodSkeletonsAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new AG_BloodSkeletonsAddonDeed();
			}
		}

		[ Constructable ]
		public AG_BloodSkeletonsAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 7387 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 7387 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 7387 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 7377 );
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 7378 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 7381 );
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 7382 );
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 7383 );
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 7384 );
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 7375 );
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 7376 );
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 7387 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 6658 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 6657 );
			AddComponent( ac, 2, 1, 6 );
			ac = new AddonComponent( 5742 );
			ac.Hue = 1;
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 7379 );
			AddComponent( ac, 0, 2, 0 );
			ac = new AddonComponent( 7380 );
			AddComponent( ac, 1, 2, 0 );
			ac = new AddonComponent( 7373 );
			AddComponent( ac, -1, 2, 0 );
			ac = new AddonComponent( 7374 );
			AddComponent( ac, 2, 2, 0 );

		}

		public AG_BloodSkeletonsAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class AG_BloodSkeletonsAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new AG_BloodSkeletonsAddon();
			}
		}

		[Constructable]
		public AG_BloodSkeletonsAddonDeed()
		{
			Name = "AG_BloodSkeletons";
		}

		public AG_BloodSkeletonsAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}