/////////////////////////////////////
//**Generated by Ryan**//
/////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
    public class GlovesoftheForsaken : PlateGloves, ITokunoDyable
	{
	 	public override int ArtifactRarity{ get{ return 10; } }
	 	public override int InitMinHits{ get{ return 255; } }
	 	public override int InitMaxHits{ get{ return 255; } }

	 	[Constructable]
	 	public GlovesoftheForsaken()
	 	{
	 	 	Name = "Gloves of the Forsaken";
	 	 	Hue = 1418;
	 	 	ArmorAttributes.MageArmor = 1;
	 	 	ArmorAttributes.SelfRepair = 3;
			Attributes.BonusDex = 2;
			Attributes.BonusHits = 5;
            EnergyBonus = 5;
            PoisonBonus = 5;
            FireBonus = 5;
            ColdBonus = 5;
			PhysicalBonus = 10;
			Attributes.DefendChance = 10;
			Attributes.Luck = 100;
			Attributes.NightSight = 1;
			Attributes.RegenMana = 2;
			Attributes.SpellDamage = 10;
	 	}

	 	public GlovesoftheForsaken(Serial serial) : base( serial )
	 	{
	 	}
	 	public override void Serialize( GenericWriter writer )
	 	{
	 	 	base.Serialize( writer );

	 	 	writer.Write( (int) 0 );
	 	}
	 	public override void Deserialize(GenericReader reader)
	 	{
	 	 	base.Deserialize( reader );

	 	 	int version = reader.ReadInt();
	 	}
	}
}
