/////////////////////////////////////
//**Generated by Ryans Scripts**//
/////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
    public class GorgetoftheForsaken : PlateGorget, ITokunoDyable
	{
	 	public override int ArtifactRarity{ get{ return 10; } }
	 	public override int InitMinHits{ get{ return 255; } }
	 	public override int InitMaxHits{ get{ return 255; } }

	 	[Constructable]
	 	public GorgetoftheForsaken()
	 	{
	 	 	Name = "Gorget of the Forsaken";
	 	 	Hue = 1418;
	 	 	ArmorAttributes.MageArmor = 1;
	 	 	ArmorAttributes.SelfRepair = 3;
            PhysicalBonus = 10;
            PoisonBonus = 10;
            EnergyBonus = 10;
            ColdBonus = 10;
            FireBonus = 10;
	 	 	Attributes.AttackChance = 10;
	 	 	Attributes.BonusHits = 5;
	 	 	Attributes.BonusStr = 5;
	 	 	Attributes.DefendChance = 5;
	 	 	Attributes.ReflectPhysical = 10;
	 	 	Attributes.RegenHits = 2;
	 	 	Attributes.RegenMana = 3;
	 	 	Attributes.RegenStam = 2;
	 	 	Attributes.SpellDamage = 5;
	 	 	Attributes.WeaponSpeed = 5;
	 	 	Attributes.NightSight = 1;
	 	}

	 	public GorgetoftheForsaken(Serial serial) : base( serial )
	 	{
	 	}
	 	public override void Serialize( GenericWriter writer )
	 	{
	 	 	base.Serialize( writer );

	 	 	writer.Write( (int) 0 );
	 	}
	 	public override void Deserialize(GenericReader reader)
	 	{
	 	 	base.Deserialize( reader );

	 	 	int version = reader.ReadInt();
	 	}
	}
}
