/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class AG_17x9brooksouthAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new AG_17x9brooksouthAddonDeed();
			}
		}

		[ Constructable ]
		public AG_17x9brooksouthAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 3332 );
			AddComponent( ac, 3, 2, 0 );
			ac = new AddonComponent( 8752 );
			AddComponent( ac, 3, -3, 0 );
			ac = new AddonComponent( 3332 );
			AddComponent( ac, 2, -2, 0 );
			ac = new AddonComponent( 13603 );
			AddComponent( ac, 0, -2, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 1, -4, 0 );
			ac = new AddonComponent( 3209 );
			AddComponent( ac, -2, -3, 0 );
			ac = new AddonComponent( 6045 );
			AddComponent( ac, 3, 3, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 1, -3, 0 );
			ac = new AddonComponent( 8134 );
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 3204 );
			AddComponent( ac, 3, -1, 0 );
			ac = new AddonComponent( 7038 );
			AddComponent( ac, 2, -5, 0 );
			ac = new AddonComponent( 3332 );
			AddComponent( ac, -1, -2, 0 );
			ac = new AddonComponent( 3332 );
			AddComponent( ac, -2, 3, 0 );
			ac = new AddonComponent( 6052 );
			AddComponent( ac, -2, 2, 0 );
			ac = new AddonComponent( 3518 );
			AddComponent( ac, 3, 4, 0 );
			ac = new AddonComponent( 10084 );
			AddComponent( ac, -2, -6, 7 );
			ac = new AddonComponent( 3208 );
			AddComponent( ac, 4, 4, 0 );
			ac = new AddonComponent( 3208 );
			AddComponent( ac, 3, -3, 0 );
			ac = new AddonComponent( 3209 );
			AddComponent( ac, 4, 0, 0 );
			ac = new AddonComponent( 3149 );
			AddComponent( ac, 4, -3, 0 );
			ac = new AddonComponent( 3211 );
			AddComponent( ac, -3, 4, 0 );
			ac = new AddonComponent( 6057 );
			AddComponent( ac, 2, 2, 0 );
			ac = new AddonComponent( 3223 );
			AddComponent( ac, -2, 0, 0 );
			ac = new AddonComponent( 6045 );
			AddComponent( ac, 3, 5, 0 );
			ac = new AddonComponent( 6473 );
			AddComponent( ac, -1, -6, 5 );
			ac = new AddonComponent( 6046 );
			AddComponent( ac, 2, -2, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, -1, 5, 0 );
			ac = new AddonComponent( 6061 );
			AddComponent( ac, 3, 2, 0 );
			ac = new AddonComponent( 6045 );
			AddComponent( ac, 2, -3, 0 );
			ac = new AddonComponent( 6040 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 3206 );
			AddComponent( ac, -3, 2, 0 );
			ac = new AddonComponent( 6045 );
			AddComponent( ac, 4, 4, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 1, 5, 0 );
			ac = new AddonComponent( 6040 );
			AddComponent( ac, -1, 3, 0 );
			ac = new AddonComponent( 6040 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 6055 );
			AddComponent( ac, 4, 5, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 2, 5, 0 );
			ac = new AddonComponent( 631 );
			AddComponent( ac, 0, -6, 0 );
			ac = new AddonComponent( 3223 );
			AddComponent( ac, 3, -2, 0 );
			ac = new AddonComponent( 3204 );
			AddComponent( ac, 3, -5, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, -1, -4, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 1, 3, 0 );
			ac = new AddonComponent( 6040 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 6040 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 3204 );
			AddComponent( ac, -2, -1, 0 );
			ac = new AddonComponent( 13484 );
			AddComponent( ac, 1, 2, 0 );
			ac = new AddonComponent( 631 );
			AddComponent( ac, 1, -6, 0 );
			ac = new AddonComponent( 3149 );
			AddComponent( ac, -3, -3, 0 );
			ac = new AddonComponent( 3231 );
			AddComponent( ac, 3, 1, 0 );
			ac = new AddonComponent( 13579 );
			AddComponent( ac, 1, -4, 0 );
			ac = new AddonComponent( 6040 );
			AddComponent( ac, 0, 2, 0 );
			ac = new AddonComponent( 3332 );
			AddComponent( ac, -2, 2, 0 );
			ac = new AddonComponent( 3149 );
			AddComponent( ac, -3, 0, 0 );
			ac = new AddonComponent( 3518 );
			AddComponent( ac, 0, 5, 0 );
			ac = new AddonComponent( 3211 );
			AddComponent( ac, 2, -4, 0 );
			ac = new AddonComponent( 13579 );
			AddComponent( ac, 0, -4, 0 );
			ac = new AddonComponent( 3223 );
			AddComponent( ac, -3, 5, 0 );
			ac = new AddonComponent( 3521 );
			ac.Hue = 1150;
			AddComponent( ac, 0, 5, 0 );
			ac = new AddonComponent( 3521 );
			ac.Hue = 1150;
			AddComponent( ac, 3, 4, 0 );
			ac = new AddonComponent( 3272 );
			AddComponent( ac, -2, -2, 0 );
			ac = new AddonComponent( 13579 );
			AddComponent( ac, -1, -4, 0 );
			ac = new AddonComponent( 633 );
			AddComponent( ac, 1, -4, 0 );
			ac = new AddonComponent( 633 );
			AddComponent( ac, -2, -4, 0 );
			ac = new AddonComponent( 636 );
			AddComponent( ac, 1, -5, 1 );
			ac = new AddonComponent( 3241 );
			AddComponent( ac, -3, 3, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 2, 4, 0 );
			ac = new AddonComponent( 3521 );
			ac.Hue = 1150;
			AddComponent( ac, -1, 4, 0 );
			ac = new AddonComponent( 8134 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 13488 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 6051 );
			AddComponent( ac, -2, 3, 0 );
			ac = new AddonComponent( 8751 );
			AddComponent( ac, 4, 2, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 0, -4, 0 );
			ac = new AddonComponent( 6052 );
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 7038 );
			AddComponent( ac, 2, -6, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 0, -5, 5 );
			ac = new AddonComponent( 3149 );
			AddComponent( ac, -3, -8, 0 );
			ac = new AddonComponent( 631 );
			AddComponent( ac, -1, -6, 0 );
			ac = new AddonComponent( 13484 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 6040 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, -2, 5, 0 );
			ac = new AddonComponent( 3231 );
			AddComponent( ac, 3, -4, 0 );
			ac = new AddonComponent( 6052 );
			AddComponent( ac, -3, 5, 0 );
			ac = new AddonComponent( 13603 );
			AddComponent( ac, 1, -2, 0 );
			ac = new AddonComponent( 6049 );
			AddComponent( ac, 3, 5, 0 );
			ac = new AddonComponent( 3332 );
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 3333 );
			AddComponent( ac, 2, -3, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 1, -5, 5 );
			ac = new AddonComponent( 6045 );
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 3333 );
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 6051 );
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 6051 );
			AddComponent( ac, -3, 4, 0 );
			ac = new AddonComponent( 13488 );
			AddComponent( ac, 1, 3, 0 );
			ac = new AddonComponent( 3212 );
			AddComponent( ac, -2, 2, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, -2, 4, 0 );
			ac = new AddonComponent( 6040 );
			AddComponent( ac, -1, 2, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, -1, -4, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 0, -5, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 2, 3, 0 );
			ac = new AddonComponent( 7038 );
			AddComponent( ac, -1, -3, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, -1, -5, 5 );
			ac = new AddonComponent( 3333 );
			AddComponent( ac, 3, 3, 0 );
			ac = new AddonComponent( 3208 );
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, -2, 4, 0 );
			ac = new AddonComponent( 634 );
			AddComponent( ac, -2, -6, 0 );
			ac = new AddonComponent( 6051 );
			AddComponent( ac, -1, -2, 0 );
			ac = new AddonComponent( 13597 );
			AddComponent( ac, 1, -3, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 0, 4, 0 );
			ac = new AddonComponent( 6046 );
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 1, -2, 0 );
			ac = new AddonComponent( 8134 );
			AddComponent( ac, 2, 3, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 1, 4, 0 );
			ac = new AddonComponent( 3518 );
			AddComponent( ac, -1, 4, 0 );
			ac = new AddonComponent( 3223 );
			AddComponent( ac, 3, 0, 0 );
			ac = new AddonComponent( 3206 );
			AddComponent( ac, 4, 3, 0 );
			ac = new AddonComponent( 6051 );
			AddComponent( ac, -2, 1, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, -1, -5, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 0, 5, 0 );
			ac = new AddonComponent( 13597 );
			AddComponent( ac, 0, -3, 0 );
			ac = new AddonComponent( 6040 );
			AddComponent( ac, 0, 3, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 3, 4, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 0, -2, 0 );
			ac = new AddonComponent( 3223 );
			AddComponent( ac, 0, -6, 4 );
			ac = new AddonComponent( 636 );
			AddComponent( ac, -2, -5, 0 );
			ac = new AddonComponent( 3332 );
			AddComponent( ac, 3, 5, 0 );
			ac = new AddonComponent( 6045 );
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 0, -3, 0 );
			ac = new AddonComponent( 3204 );
			AddComponent( ac, 2, 2, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 6040 );
			AddComponent( ac, 1, 2, 0 );
			ac = new AddonComponent( 6052 );
			AddComponent( ac, -2, 4, 0 );
			ac = new AddonComponent( 3209 );
			AddComponent( ac, -3, 1, 0 );
			ac = new AddonComponent( 3149 );
			AddComponent( ac, 3, -6, 0 );
			ac = new AddonComponent( 6054 );
			AddComponent( ac, -2, 0, 0 );
			ac = new AddonComponent( 3332 );
			AddComponent( ac, 2, 7, 0 );
			ac = new AddonComponent( 6049 );
			AddComponent( ac, -2, 6, 0 );
			ac = new AddonComponent( 3209 );
			AddComponent( ac, 3, 7, 0 );
			ac = new AddonComponent( 3259 );
			AddComponent( ac, -3, 7, 0 );
			ac = new AddonComponent( 3209 );
			AddComponent( ac, -2, 8, 0 );
			ac = new AddonComponent( 6045 );
			AddComponent( ac, 1, 7, 0 );
			ac = new AddonComponent( 6056 );
			AddComponent( ac, -2, 7, 0 );
			ac = new AddonComponent( 6049 );
			AddComponent( ac, -1, 7, 0 );
			ac = new AddonComponent( 6045 );
			AddComponent( ac, 2, 6, 0 );
			ac = new AddonComponent( 3518 );
			AddComponent( ac, 1, 6, 0 );
			ac = new AddonComponent( 3149 );
			AddComponent( ac, 3, 8, 0 );
			ac = new AddonComponent( 3332 );
			AddComponent( ac, 0, 7, 0 );
			ac = new AddonComponent( 3223 );
			AddComponent( ac, -2, 7, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 0, 7, 0 );
			ac = new AddonComponent( 3211 );
			AddComponent( ac, 0, 7, 0 );
			ac = new AddonComponent( 3204 );
			AddComponent( ac, -3, 6, 0 );
			ac = new AddonComponent( 3149 );
			AddComponent( ac, -3, 8, 0 );
			ac = new AddonComponent( 3149 );
			AddComponent( ac, 2, 7, 0 );
			ac = new AddonComponent( 3211 );
			AddComponent( ac, 3, 6, 0 );
			ac = new AddonComponent( 3204 );
			AddComponent( ac, 1, 8, 0 );
			ac = new AddonComponent( 3332 );
			AddComponent( ac, -1, 8, 0 );
			ac = new AddonComponent( 6055 );
			AddComponent( ac, 1, 8, 0 );
			ac = new AddonComponent( 3333 );
			AddComponent( ac, -2, 6, 0 );
			ac = new AddonComponent( 6049 );
			AddComponent( ac, 2, 6, 0 );
			ac = new AddonComponent( 6049 );
			AddComponent( ac, 0, 8, 0 );
			ac = new AddonComponent( 6055 );
			AddComponent( ac, 3, 6, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 1, 6, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 0, 6, 0 );
			ac = new AddonComponent( 3333 );
			AddComponent( ac, 1, 7, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, -1, 6, 0 );
			ac = new AddonComponent( 3206 );
			AddComponent( ac, -1, 7, 0 );
			ac = new AddonComponent( 6056 );
			AddComponent( ac, -3, 6, 0 );

		}

		public AG_17x9brooksouthAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class AG_17x9brooksouthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new AG_17x9brooksouthAddon();
			}
		}

		[Constructable]
		public AG_17x9brooksouthAddonDeed()
		{
			Name = "AG_17x9brooksouth";
		}

		public AG_17x9brooksouthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}