/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class AG_4x4fireplacecornerAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new AG_4x4fireplacecornerAddonDeed();
			}
		}

		[ Constructable ]
		public AG_4x4fireplacecornerAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 4850 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 9225 );
			AddComponent( ac, 1, 0, 2 );
			ac = new AddonComponent( 4850 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 6571 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, -1, 0, 2 );
			ac = new AddonComponent( 4850 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 13849 );
			AddComponent( ac, -2, -2, 0 );
			ac = new AddonComponent( 13898 );
			AddComponent( ac, -2, 0, 0 );
			ac = new AddonComponent( 703 );
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 13896 );
			AddComponent( ac, -2, 2, 0 );
			ac = new AddonComponent( 6571 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 0, -1, 2 );
			ac = new AddonComponent( 660 );
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 4850 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 13898 );
			AddComponent( ac, -2, -1, 0 );
			ac = new AddonComponent( 4850 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 13897 );
			AddComponent( ac, -1, -2, 0 );
			ac = new AddonComponent( 13897 );
			AddComponent( ac, 1, -2, 0 );
			ac = new AddonComponent( 701 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 13897 );
			AddComponent( ac, 0, -2, 0 );
			ac = new AddonComponent( 13898 );
			AddComponent( ac, -2, 1, 0 );
			ac = new AddonComponent( 702 );
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 704 );
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 9226 );
			AddComponent( ac, 0, 1, 2 );
			ac = new AddonComponent( 13843 );
			AddComponent( ac, -1, 2, 0 );
			ac = new AddonComponent( 13895 );
			AddComponent( ac, 2, -2, 0 );
			ac = new AddonComponent( 13843 );
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 13843 );
			AddComponent( ac, 2, -1, 0 );

		}

		public AG_4x4fireplacecornerAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class AG_4x4fireplacecornerAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new AG_4x4fireplacecornerAddon();
			}
		}

		[Constructable]
		public AG_4x4fireplacecornerAddonDeed()
		{
			Name = "AG_4x4fireplacecorner";
		}

		public AG_4x4fireplacecornerAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}