/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class AG_8x8minotaurAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new AG_8x8minotaurAddonDeed();
			}
		}

		[ Constructable ]
		public AG_8x8minotaurAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 13748 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 13748 );
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 13748 );
			AddComponent( ac, 3, -1, 0 );
			ac = new AddonComponent( 3813 );
			AddComponent( ac, -1, 2, 0 );
			ac = new AddonComponent( 8708 );
			AddComponent( ac, 0, 2, 2 );
			ac = new AddonComponent( 7400 );
			AddComponent( ac, 3, 0, 0 );
			ac = new AddonComponent( 7040 );
			AddComponent( ac, 0, 2, 1 );
			ac = new AddonComponent( 6873 );
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 13748 );
			AddComponent( ac, 3, 0, 0 );
			ac = new AddonComponent( 13748 );
			AddComponent( ac, -1, -2, 0 );
			ac = new AddonComponent( 6923 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 13748 );
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 13748 );
			AddComponent( ac, 3, 2, 0 );
			ac = new AddonComponent( 6926 );
			AddComponent( ac, 0, 2, 0 );
			ac = new AddonComponent( 13748 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 6924 );
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 13748 );
			AddComponent( ac, 0, -2, 0 );
			ac = new AddonComponent( 6872 );
			AddComponent( ac, 3, 1, 0 );
			ac = new AddonComponent( 4650 );
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 8700 );
			AddComponent( ac, -2, 0, 0 );
			ac = new AddonComponent( 13748 );
			AddComponent( ac, -2, 2, 0 );
			ac = new AddonComponent( 3811 );
			AddComponent( ac, 0, 2, 0 );
			ac = new AddonComponent( 13748 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 6925 );
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 13748 );
			AddComponent( ac, 3, -2, 0 );
			ac = new AddonComponent( 13748 );
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 6922 );
			AddComponent( ac, -1, -2, 0 );
			ac = new AddonComponent( 13748 );
			AddComponent( ac, 2, 2, 0 );
			ac = new AddonComponent( 13748 );
			AddComponent( ac, 3, 1, 0 );
			ac = new AddonComponent( 13748 );
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 6873 );
			AddComponent( ac, 2, 2, 0 );
			ac = new AddonComponent( 6873 );
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 6877 );
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 12404 );
			ac.Hue = 1150;
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 13748 );
			AddComponent( ac, -2, 1, 0 );
			ac = new AddonComponent( 12406 );
			ac.Hue = 1150;
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 3814 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 6923 );
			AddComponent( ac, 3, -2, 0 );
			ac = new AddonComponent( 13748 );
			AddComponent( ac, -2, -2, 0 );
			ac = new AddonComponent( 6873 );
			AddComponent( ac, 1, 2, 0 );
			ac = new AddonComponent( 13748 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 13748 );
			AddComponent( ac, -2, 0, 0 );
			ac = new AddonComponent( 13748 );
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 13748 );
			AddComponent( ac, 1, -2, 0 );
			ac = new AddonComponent( 6875 );
			AddComponent( ac, 2, 1, 1 );
			ac = new AddonComponent( 7391 );
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 13748 );
			AddComponent( ac, 2, -2, 0 );
			ac = new AddonComponent( 13748 );
			AddComponent( ac, -2, -1, 0 );
			ac = new AddonComponent( 13748 );
			AddComponent( ac, -1, 2, 0 );
			ac = new AddonComponent( 4454 );
			AddComponent( ac, 0, -2, 0 );
			ac = new AddonComponent( 13748 );
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 13748 );
			AddComponent( ac, 1, 2, 0 );
			ac = new AddonComponent( 13748 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 13748 );
			AddComponent( ac, 0, 2, 0 );
			ac = new AddonComponent( 6875 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 13748 );
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 6925 );
			AddComponent( ac, 2, -2, 0 );
			ac = new AddonComponent( 12405 );
			ac.Hue = 1150;
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 4650 );
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 4650 );
			AddComponent( ac, -2, 3, 0 );
			ac = new AddonComponent( 13748 );
			AddComponent( ac, -2, 3, 0 );
			ac = new AddonComponent( 6922 );
			AddComponent( ac, -1, 3, 0 );
			ac = new AddonComponent( 3812 );
			AddComponent( ac, 0, 3, 0 );
			ac = new AddonComponent( 13748 );
			AddComponent( ac, 1, 3, 0 );
			ac = new AddonComponent( 13748 );
			AddComponent( ac, -1, 3, 0 );
			ac = new AddonComponent( 13748 );
			AddComponent( ac, 3, 3, 0 );
			ac = new AddonComponent( 7040 );
			AddComponent( ac, 0, 3, 10 );
			ac = new AddonComponent( 13748 );
			AddComponent( ac, 2, 3, 0 );
			ac = new AddonComponent( 4651 );
			AddComponent( ac, 3, 3, 0 );
			ac = new AddonComponent( 6924 );
			AddComponent( ac, 3, 3, 0 );
			ac = new AddonComponent( 13748 );
			AddComponent( ac, 0, 3, 0 );

		}

		public AG_8x8minotaurAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class AG_8x8minotaurAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new AG_8x8minotaurAddon();
			}
		}

		[Constructable]
		public AG_8x8minotaurAddonDeed()
		{
			Name = "AG_8x8minotaur";
		}

		public AG_8x8minotaurAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}