/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class AG_8x8minotaursouthAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new AG_8x8minotaursouthAddonDeed();
			}
		}

		[ Constructable ]
		public AG_8x8minotaursouthAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 4454 );
			AddComponent( ac, 0, -2, 0 );
			ac = new AddonComponent( 6874 );
			AddComponent( ac, 0, 2, 0 );
			ac = new AddonComponent( 4650 );
			AddComponent( ac, -2, 3, 0 );
			ac = new AddonComponent( 6924 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 13747 );
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 13747 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 13747 );
			AddComponent( ac, 0, -2, 0 );
			ac = new AddonComponent( 13747 );
			AddComponent( ac, -1, 3, 0 );
			ac = new AddonComponent( 13747 );
			AddComponent( ac, -1, 2, 0 );
			ac = new AddonComponent( 13747 );
			AddComponent( ac, 0, 3, 0 );
			ac = new AddonComponent( 13747 );
			AddComponent( ac, 0, 2, 0 );
			ac = new AddonComponent( 13747 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 12397 );
			ac.Hue = 1150;
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 13747 );
			AddComponent( ac, -2, 0, 0 );
			ac = new AddonComponent( 13747 );
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 13747 );
			AddComponent( ac, -2, 1, 0 );
			ac = new AddonComponent( 13747 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 3811 );
			AddComponent( ac, 0, 3, 0 );
			ac = new AddonComponent( 13747 );
			AddComponent( ac, -2, 3, 0 );
			ac = new AddonComponent( 13747 );
			AddComponent( ac, -1, -2, 0 );
			ac = new AddonComponent( 3813 );
			AddComponent( ac, -1, 2, 0 );
			ac = new AddonComponent( 13747 );
			AddComponent( ac, -2, -1, 0 );
			ac = new AddonComponent( 13747 );
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 3812 );
			AddComponent( ac, -1, 3, 0 );
			ac = new AddonComponent( 13747 );
			AddComponent( ac, -2, -2, 0 );
			ac = new AddonComponent( 4650 );
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 13747 );
			AddComponent( ac, -2, 2, 0 );
			ac = new AddonComponent( 6923 );
			AddComponent( ac, -1, -2, 0 );
			ac = new AddonComponent( 6922 );
			AddComponent( ac, 0, 3, 0 );
			ac = new AddonComponent( 8700 );
			AddComponent( ac, -2, 0, 0 );
			ac = new AddonComponent( 8708 );
			AddComponent( ac, 0, 2, 0 );
			ac = new AddonComponent( 6878 );
			AddComponent( ac, 3, -1, 0 );
			ac = new AddonComponent( 13747 );
			AddComponent( ac, 2, 3, 0 );
			ac = new AddonComponent( 13747 );
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 13747 );
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 13747 );
			AddComponent( ac, 2, 2, 0 );
			ac = new AddonComponent( 7384 );
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 4653 );
			AddComponent( ac, 3, 3, 0 );
			ac = new AddonComponent( 6879 );
			AddComponent( ac, 3, 0, 0 );
			ac = new AddonComponent( 6879 );
			AddComponent( ac, 3, 1, 0 );
			ac = new AddonComponent( 13747 );
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 6879 );
			AddComponent( ac, 3, 2, 0 );
			ac = new AddonComponent( 4650 );
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 7400 );
			AddComponent( ac, 3, 1, 0 );
			ac = new AddonComponent( 7406 );
			AddComponent( ac, 1, 3, 0 );
			ac = new AddonComponent( 13747 );
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 12398 );
			ac.Hue = 1150;
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 6873 );
			AddComponent( ac, 1, 2, 0 );
			ac = new AddonComponent( 13747 );
			AddComponent( ac, 3, -1, 0 );
			ac = new AddonComponent( 13747 );
			AddComponent( ac, 3, 0, 0 );
			ac = new AddonComponent( 13747 );
			AddComponent( ac, 3, -2, 0 );
			ac = new AddonComponent( 6922 );
			AddComponent( ac, 2, 3, 0 );
			ac = new AddonComponent( 13747 );
			AddComponent( ac, 1, 3, 0 );
			ac = new AddonComponent( 13747 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 13747 );
			AddComponent( ac, 1, -2, 0 );
			ac = new AddonComponent( 6875 );
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 13747 );
			AddComponent( ac, 2, -2, 0 );
			ac = new AddonComponent( 7384 );
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 13747 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 13747 );
			AddComponent( ac, 1, 2, 0 );
			ac = new AddonComponent( 6921 );
			AddComponent( ac, 3, 2, 0 );
			ac = new AddonComponent( 13747 );
			AddComponent( ac, 3, 2, 0 );
			ac = new AddonComponent( 6924 );
			AddComponent( ac, 3, -2, 0 );
			ac = new AddonComponent( 6926 );
			AddComponent( ac, 1, -2, 0 );
			ac = new AddonComponent( 13747 );
			AddComponent( ac, 3, 1, 0 );
			ac = new AddonComponent( 6923 );
			AddComponent( ac, 2, -2, 0 );
			ac = new AddonComponent( 4650 );
			AddComponent( ac, 2, 2, 0 );
			ac = new AddonComponent( 6873 );
			AddComponent( ac, 2, 2, 0 );
			ac = new AddonComponent( 12396 );
			ac.Hue = 1150;
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 7393 );
			AddComponent( ac, 2, 3, 0 );
			ac = new AddonComponent( 13747 );
			AddComponent( ac, 3, 3, 0 );
			ac = new AddonComponent( 6924 );
			AddComponent( ac, 3, -1, 0 );
			ac = new AddonComponent( 7391 );
			AddComponent( ac, 1, 3, 0 );
			ac = new AddonComponent( 6877 );
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 6876 );
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 6872 );
			AddComponent( ac, 3, 0, 0 );

		}

		public AG_8x8minotaursouthAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class AG_8x8minotaursouthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new AG_8x8minotaursouthAddon();
			}
		}

		[Constructable]
		public AG_8x8minotaursouthAddonDeed()
		{
			Name = "AG_8x8minotaursouth";
		}

		public AG_8x8minotaursouthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}