/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class AG_windowboxsouth1Addon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new AG_windowboxsouth1AddonDeed();
			}
		}

		[ Constructable ]
		public AG_windowboxsouth1Addon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 2826 );
			ac.Name = "window box";
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 3223 );
			AddComponent( ac, 0, 0, 5 );
			ac = new AddonComponent( 6811 );
			AddComponent( ac, 0, 0, 11 );
			ac = new AddonComponent( 9037 );
			AddComponent( ac, 0, 0, 2 );
			ac = new AddonComponent( 3152 );
			AddComponent( ac, 0, 0, 3 );

		}

		public AG_windowboxsouth1Addon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class AG_windowboxsouth1AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new AG_windowboxsouth1Addon();
			}
		}

		[Constructable]
		public AG_windowboxsouth1AddonDeed()
		{
			Name = "AG_windowboxsouth1";
		}

		public AG_windowboxsouth1AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}