/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class AG_windowboxeast1Addon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new AG_windowboxeast1AddonDeed();
			}
		}

		[ Constructable ]
		public AG_windowboxeast1Addon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 9036 );
			AddComponent( ac, 0, 1, 12 );
			ac = new AddonComponent( 3208 );
			AddComponent( ac, 0, 0, 6 );
			ac = new AddonComponent( 9036 );
			AddComponent( ac, 0, 0, 11 );
			ac = new AddonComponent( 3151 );
			AddComponent( ac, 0, 0, 4 );
			ac = new AddonComponent( 3223 );
			AddComponent( ac, 0, 0, 1 );
			ac = new AddonComponent( 2825 );
			ac.Name = "Window box";
			AddComponent( ac, 0, 0, 0 );

		}

		public AG_windowboxeast1Addon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class AG_windowboxeast1AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new AG_windowboxeast1Addon();
			}
		}

		[Constructable]
		public AG_windowboxeast1AddonDeed()
		{
			Name = "AG_windowboxeast1";
		}

		public AG_windowboxeast1AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}