/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class RuinsAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new RuinsAddonDeed();
			}
		}

		[ Constructable ]
		public RuinsAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 962 );
			AddComponent( ac, -4, -4, 0 );
			ac = new AddonComponent( 962 );
			AddComponent( ac, -4, -4, 10 );
			ac = new AddonComponent( 951 );
			AddComponent( ac, -4, -3, 0 );
			ac = new AddonComponent( 964 );
			AddComponent( ac, 3, -3, 0 );
			ac = new AddonComponent( 954 );
			AddComponent( ac, 1, -4, 0 );
			ac = new AddonComponent( 965 );
			AddComponent( ac, -2, -4, 0 );
			ac = new AddonComponent( 957 );
			AddComponent( ac, -3, -4, 10 );
			ac = new AddonComponent( 956 );
			AddComponent( ac, 3, -4, 0 );
			ac = new AddonComponent( 960 );
			AddComponent( ac, -3, -4, 0 );
			ac = new AddonComponent( 1322 );
			AddComponent( ac, 1, -3, 0 );
			ac = new AddonComponent( 1322 );
			AddComponent( ac, -2, -3, 0 );
			ac = new AddonComponent( 3248 );
			AddComponent( ac, -2, -3, 0 );
			ac = new AddonComponent( 957 );
			AddComponent( ac, -1, -4, 0 );
			ac = new AddonComponent( 954 );
			AddComponent( ac, -3, 5, 0 );
			ac = new AddonComponent( 1117 );
			AddComponent( ac, -3, 0, 0 );
			ac = new AddonComponent( 1118 );
			AddComponent( ac, -3, -1, 0 );
			ac = new AddonComponent( 969 );
			AddComponent( ac, -4, 0, 0 );
			ac = new AddonComponent( 961 );
			AddComponent( ac, -4, 1, 0 );
			ac = new AddonComponent( 959 );
			AddComponent( ac, 3, 3, 10 );
			ac = new AddonComponent( 966 );
			AddComponent( ac, -4, 1, 10 );
			ac = new AddonComponent( 966 );
			AddComponent( ac, -4, 2, 0 );
			ac = new AddonComponent( 953 );
			AddComponent( ac, 3, 1, 0 );
			ac = new AddonComponent( 963 );
			AddComponent( ac, 2, 3, 0 );
			ac = new AddonComponent( 898 );
			AddComponent( ac, 3, -1, 0 );
			ac = new AddonComponent( 966 );
			AddComponent( ac, 3, 0, 0 );
			ac = new AddonComponent( 951 );
			AddComponent( ac, -3, 3, 0 );
			ac = new AddonComponent( 952 );
			AddComponent( ac, -1, 5, 0 );
			ac = new AddonComponent( 955 );
			AddComponent( ac, -2, -2, 0 );
			ac = new AddonComponent( 958 );
			AddComponent( ac, 3, 3, 0 );
			ac = new AddonComponent( 955 );
			AddComponent( ac, 0, 4, 0 );
			ac = new AddonComponent( 1321 );
			AddComponent( ac, 0, -2, 0 );
			ac = new AddonComponent( 3098 );
			AddComponent( ac, -2, 4, 0 );
			ac = new AddonComponent( 1321 );
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 1321 );
			AddComponent( ac, -3, 2, 0 );
			ac = new AddonComponent( 1321 );
			AddComponent( ac, -2, 3, 0 );
			ac = new AddonComponent( 1321 );
			AddComponent( ac, -1, 3, 0 );
			ac = new AddonComponent( 1321 );
			AddComponent( ac, -2, -1, 0 );
			ac = new AddonComponent( 1322 );
			AddComponent( ac, 1, 2, 0 );
			ac = new AddonComponent( 1322 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 3120 );
			AddComponent( ac, -3, 1, 0 );
			ac = new AddonComponent( 1322 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 1322 );
			AddComponent( ac, -2, 1, 0 );
			ac = new AddonComponent( 3117 );
			AddComponent( ac, -1, -2, 0 );
			ac = new AddonComponent( 3101 );
			AddComponent( ac, 1, 2, 0 );
			ac = new AddonComponent( 1322 );
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 1322 );
			AddComponent( ac, -1, -2, 0 );
			ac = new AddonComponent( 1322 );
			AddComponent( ac, 2, -2, 0 );
			ac = new AddonComponent( 1322 );
			AddComponent( ac, 3, 0, 0 );
			ac = new AddonComponent( 1322 );
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 1322 );
			AddComponent( ac, 0, 3, 0 );
			ac = new AddonComponent( 1322 );
			AddComponent( ac, -3, -2, 0 );
			ac = new AddonComponent( 3392 );
			AddComponent( ac, -3, -2, 0 );
			ac = new AddonComponent( 3244 );
			AddComponent( ac, -2, 0, 0 );
			ac = new AddonComponent( 3244 );
			AddComponent( ac, 4, 0, 0 );
			ac = new AddonComponent( 3245 );
			AddComponent( ac, 2, 4, 0 );
			ac = new AddonComponent( 964 );
			AddComponent( ac, -4, 3, 0 );
			ac = new AddonComponent( 961 );
			AddComponent( ac, -4, 4, 0 );
			ac = new AddonComponent( 953 );
			AddComponent( ac, -4, 5, 0 );
			ac = new AddonComponent( 951 );
			AddComponent( ac, -4, 5, 3 );

		}

		public RuinsAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class RuinsAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new RuinsAddon();
			}
		}

		[Constructable]
		public RuinsAddonDeed()
		{
			Name = "Ruins";
		}

		public RuinsAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}