/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class AG_12x12lighthouseAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new AG_12x12lighthouseAddonDeed();
			}
		}

		[ Constructable ]
		public AG_12x12lighthouseAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 3149 );
			AddComponent( ac, 4, 2, 16 );
			ac = new AddonComponent( 4944 );
			AddComponent( ac, 2, -1, 1 );
			ac = new AddonComponent( 7038 );
			AddComponent( ac, 3, -2, 3 );
			ac = new AddonComponent( 11901 );
			AddComponent( ac, 2, -1, 2 );
			ac = new AddonComponent( 4954 );
			AddComponent( ac, 2, 4, 0 );
			ac = new AddonComponent( 11901 );
			AddComponent( ac, 4, 2, 0 );
			ac = new AddonComponent( 6811 );
			AddComponent( ac, -3, 4, 0 );
			ac = new AddonComponent( 11901 );
			AddComponent( ac, 4, -1, 0 );
			ac = new AddonComponent( 3223 );
			AddComponent( ac, 2, -1, 2 );
			ac = new AddonComponent( 11901 );
			AddComponent( ac, 4, 4, 0 );
			ac = new AddonComponent( 11917 );
			AddComponent( ac, -3, 2, 0 );
			ac = new AddonComponent( 11894 );
			AddComponent( ac, -2, 4, 0 );
			ac = new AddonComponent( 11917 );
			AddComponent( ac, -2, 3, 0 );
			ac = new AddonComponent( 4943 );
			AddComponent( ac, -1, 2, 0 );
			ac = new AddonComponent( 3149 );
			AddComponent( ac, 4, -1, 5 );
			ac = new AddonComponent( 3149 );
			AddComponent( ac, -2, 4, 0 );
			ac = new AddonComponent( 11894 );
			AddComponent( ac, -1, 3, 0 );
			ac = new AddonComponent( 9537 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 3391 );
			AddComponent( ac, 3, -3, 0 );
			ac = new AddonComponent( 3209 );
			AddComponent( ac, 4, 0, 3 );
			ac = new AddonComponent( 11911 );
			AddComponent( ac, 4, -2, 0 );
			ac = new AddonComponent( 11911 );
			AddComponent( ac, 4, -3, 0 );
			ac = new AddonComponent( 11895 );
			AddComponent( ac, 2, 4, 0 );
			ac = new AddonComponent( 11882 );
			AddComponent( ac, -1, 3, 0 );
			ac = new AddonComponent( 11883 );
			AddComponent( ac, -2, 3, 0 );
			ac = new AddonComponent( 9537 );
			AddComponent( ac, 1, 0, 20 );
			ac = new AddonComponent( 11895 );
			AddComponent( ac, 3, 4, 0 );
			ac = new AddonComponent( 4973 );
			AddComponent( ac, -2, 3, 1 );
			ac = new AddonComponent( 3149 );
			AddComponent( ac, 2, 4, 5 );
			ac = new AddonComponent( 3149 );
			AddComponent( ac, -3, 3, 2 );
			ac = new AddonComponent( 4955 );
			AddComponent( ac, 3, 3, 5 );
			ac = new AddonComponent( 3235 );
			AddComponent( ac, -2, 3, 0 );
			ac = new AddonComponent( 11901 );
			AddComponent( ac, 2, -2, 0 );
			ac = new AddonComponent( 3235 );
			AddComponent( ac, 3, -3, 0 );
			ac = new AddonComponent( 4963 );
			AddComponent( ac, 2, -1, 1 );
			ac = new AddonComponent( 11901 );
			AddComponent( ac, 4, -2, 0 );
			ac = new AddonComponent( 4949 );
			AddComponent( ac, 0, 3, 0 );
			ac = new AddonComponent( 3204 );
			AddComponent( ac, 1, -3, 0 );
			ac = new AddonComponent( 3223 );
			AddComponent( ac, -2, 1, 0 );
			ac = new AddonComponent( 11894 );
			AddComponent( ac, 1, 4, 1 );
			ac = new AddonComponent( 3210 );
			AddComponent( ac, 3, 5, 8 );
			ac = new AddonComponent( 9553 );
			AddComponent( ac, 3, 1, 20 );
			ac = new AddonComponent( 4970 );
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 4970 );
			AddComponent( ac, 3, 0, 0 );
			ac = new AddonComponent( 4967 );
			AddComponent( ac, -3, 3, 0 );
			ac = new AddonComponent( 9545 );
			AddComponent( ac, 0, 2, 23 );
			ac = new AddonComponent( 7038 );
			AddComponent( ac, -2, 2, 5 );
			ac = new AddonComponent( 11901 );
			AddComponent( ac, 3, -1, 0 );
			ac = new AddonComponent( 3223 );
			AddComponent( ac, 4, -2, 0 );
			ac = new AddonComponent( 11911 );
			AddComponent( ac, 3, -3, 0 );
			ac = new AddonComponent( 3204 );
			AddComponent( ac, 0, 5, 10 );
			ac = new AddonComponent( 4958 );
			AddComponent( ac, 4, 1, 0 );
			ac = new AddonComponent( 11917 );
			AddComponent( ac, -2, 3, 0 );
			ac = new AddonComponent( 3210 );
			AddComponent( ac, 4, 4, 25 );
			ac = new AddonComponent( 4973 );
			AddComponent( ac, 3, 0, 5 );
			ac = new AddonComponent( 9535 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 6811 );
			AddComponent( ac, -2, 2, 0 );
			ac = new AddonComponent( 4967 );
			AddComponent( ac, -2, 2, 1 );
			ac = new AddonComponent( 4967 );
			AddComponent( ac, 4, -3, 0 );
			ac = new AddonComponent( 11901 );
			AddComponent( ac, 4, 1, 0 );
			ac = new AddonComponent( 11913 );
			AddComponent( ac, -3, 4, 0 );
			ac = new AddonComponent( 11901 );
			AddComponent( ac, -2, 1, 0 );
			ac = new AddonComponent( 3223 );
			AddComponent( ac, 1, 4, 1 );
			ac = new AddonComponent( 4957 );
			AddComponent( ac, 4, 2, 1 );
			ac = new AddonComponent( 11901 );
			AddComponent( ac, 4, 0, 0 );
			ac = new AddonComponent( 9548 );
			AddComponent( ac, 1, 3, 21 );
			ac = new AddonComponent( 11901 );
			AddComponent( ac, -2, 0, 0 );
			ac = new AddonComponent( 9539 );
			AddComponent( ac, 3, 2, 20 );
			ac = new AddonComponent( 4956 );
			AddComponent( ac, 3, 3, 1 );
			ac = new AddonComponent( 4950 );
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 4963 );
			AddComponent( ac, 4, 0, 1 );
			ac = new AddonComponent( 3149 );
			AddComponent( ac, -4, 4, 0 );
			ac = new AddonComponent( 3149 );
			AddComponent( ac, 3, -3, 5 );
			ac = new AddonComponent( 3392 );
			AddComponent( ac, -2, 0, 0 );
			ac = new AddonComponent( 6811 );
			AddComponent( ac, 4, 4, 1 );
			ac = new AddonComponent( 3207 );
			AddComponent( ac, 4, -3, 0 );
			ac = new AddonComponent( 3149 );
			AddComponent( ac, 3, 0, 2 );
			ac = new AddonComponent( 6811 );
			AddComponent( ac, 3, -1, 4 );
			ac = new AddonComponent( 3223 );
			AddComponent( ac, 0, -3, 0 );
			ac = new AddonComponent( 9545 );
			AddComponent( ac, 0, 2, 4 );
			ac = new AddonComponent( 3391 );
			AddComponent( ac, -1, 4, 0 );
			ac = new AddonComponent( 11901 );
			AddComponent( ac, 4, 3, 0 );
			ac = new AddonComponent( 4964 );
			AddComponent( ac, 3, 3, 1 );
			ac = new AddonComponent( 9551 );
			AddComponent( ac, 2, 0, 20 );
			ac = new AddonComponent( 3207 );
			AddComponent( ac, -1, 4, 5 );
			ac = new AddonComponent( 3204 );
			AddComponent( ac, -3, 2, 4 );
			ac = new AddonComponent( 3207 );
			AddComponent( ac, 4, 3, 0 );
			ac = new AddonComponent( 3149 );
			AddComponent( ac, 4, -4, 0 );
			ac = new AddonComponent( 11917 );
			AddComponent( ac, -3, 3, 0 );
			ac = new AddonComponent( 4964 );
			AddComponent( ac, 2, 3, 0 );
			ac = new AddonComponent( 9553 );
			AddComponent( ac, 3, 1, 0 );
			ac = new AddonComponent( 4967 );
			AddComponent( ac, 3, 4, 2 );
			ac = new AddonComponent( 9544 );
			AddComponent( ac, 2, 3, 20 );
			ac = new AddonComponent( 4967 );
			AddComponent( ac, 0, 4, 1 );
			ac = new AddonComponent( 11888 );
			AddComponent( ac, -1, 4, 0 );
			ac = new AddonComponent( 9535 );
			AddComponent( ac, 0, 1, 20 );
			ac = new AddonComponent( 3149 );
			AddComponent( ac, 2, -1, 16 );
			ac = new AddonComponent( 11894 );
			AddComponent( ac, 0, 4, 0 );
			ac = new AddonComponent( 3149 );
			AddComponent( ac, 4, 4, 5 );
			ac = new AddonComponent( 4951 );
			AddComponent( ac, 3, 0, 0 );
			ac = new AddonComponent( 9551 );
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 11884 );
			AddComponent( ac, -2, 2, 0 );
			ac = new AddonComponent( 3204 );
			AddComponent( ac, 1, 4, 15 );
			ac = new AddonComponent( 9548 );
			AddComponent( ac, 1, 3, 0 );
			ac = new AddonComponent( 9544 );
			AddComponent( ac, 2, 3, 1 );
			ac = new AddonComponent( 4970 );
			AddComponent( ac, 4, 1, 2 );
			ac = new AddonComponent( 11895 );
			AddComponent( ac, 2, 3, 0 );
			ac = new AddonComponent( 4953 );
			AddComponent( ac, 1, 3, 0 );
			ac = new AddonComponent( 4945 );
			AddComponent( ac, 2, -2, 0 );
			ac = new AddonComponent( 4952 );
			AddComponent( ac, 4, -1, 0 );
			ac = new AddonComponent( 4970 );
			AddComponent( ac, 1, 4, 0 );
			ac = new AddonComponent( 4973 );
			AddComponent( ac, 1, 4, 1 );
			ac = new AddonComponent( 4963 );
			AddComponent( ac, -1, 3, 1 );
			ac = new AddonComponent( 9539 );
			AddComponent( ac, 3, 2, 0 );

		}

		public AG_12x12lighthouseAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class AG_12x12lighthouseAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new AG_12x12lighthouseAddon();
			}
		}

		[Constructable]
		public AG_12x12lighthouseAddonDeed()
		{
			Name = "AG_12x12lighthouse";
		}

		public AG_12x12lighthouseAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}