/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class AG_17x9brookeastAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new AG_17x9brookeastAddonDeed();
			}
		}

		[ Constructable ]
		public AG_17x9brookeastAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 3149 );
			AddComponent( ac, -7, -3, 0 );
			ac = new AddonComponent( 13446 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 3149 );
			AddComponent( ac, 8, 0, 0 );
			ac = new AddonComponent( 3209 );
			AddComponent( ac, 7, -2, 0 );
			ac = new AddonComponent( 10084 );
			AddComponent( ac, -4, -2, 9 );
			ac = new AddonComponent( 6047 );
			AddComponent( ac, 3, -2, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 4, -1, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 8129 );
			AddComponent( ac, 4, -1, 0 );
			ac = new AddonComponent( 6054 );
			AddComponent( ac, 0, -2, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 4, 0, 0 );
			ac = new AddonComponent( 6047 );
			AddComponent( ac, 5, -3, 0 );
			ac = new AddonComponent( 13451 );
			AddComponent( ac, 4, -2, 0 );
			ac = new AddonComponent( 6047 );
			AddComponent( ac, 1, -2, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 5, -1, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, -3, -1, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 5, -2, 0 );
			ac = new AddonComponent( 3206 );
			AddComponent( ac, 3, -3, 0 );
			ac = new AddonComponent( 6060 );
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 6, 0, 0 );
			ac = new AddonComponent( 6063 );
			AddComponent( ac, 6, -2, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 6, -1, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 3332 );
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 3521 );
			ac.Hue = 1150;
			AddComponent( ac, 5, -1, 0 );
			ac = new AddonComponent( 6053 );
			AddComponent( ac, 7, -2, 0 );
			ac = new AddonComponent( 6053 );
			AddComponent( ac, 6, -3, 0 );
			ac = new AddonComponent( 6063 );
			AddComponent( ac, 3, -3, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 4, -2, 0 );
			ac = new AddonComponent( 3332 );
			AddComponent( ac, 2, -2, 0 );
			ac = new AddonComponent( 6048 );
			AddComponent( ac, 4, -3, 0 );
			ac = new AddonComponent( 3241 );
			AddComponent( ac, 1, -3, 0 );
			ac = new AddonComponent( 3272 );
			AddComponent( ac, -1, -2, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, -4, 0, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, -4, -1, 0 );
			ac = new AddonComponent( 3206 );
			AddComponent( ac, 5, -3, 0 );
			ac = new AddonComponent( 3204 );
			AddComponent( ac, 4, -3, 0 );
			ac = new AddonComponent( 3521 );
			ac.Hue = 1150;
			AddComponent( ac, 7, 0, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 13451 );
			AddComponent( ac, 1, -2, 0 );
			ac = new AddonComponent( 635 );
			AddComponent( ac, -5, -2, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 6474 );
			AddComponent( ac, -5, -1, 5 );
			ac = new AddonComponent( 6048 );
			AddComponent( ac, 2, -2, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, -4, 0, 5 );
			ac = new AddonComponent( 636 );
			AddComponent( ac, -5, 0, 0 );
			ac = new AddonComponent( 13555 );
			AddComponent( ac, -2, 0, 0 );
			ac = new AddonComponent( 632 );
			AddComponent( ac, -3, -2, 0 );
			ac = new AddonComponent( 3332 );
			AddComponent( ac, 6, -2, 0 );
			ac = new AddonComponent( 7038 );
			AddComponent( ac, -2, -1, 0 );
			ac = new AddonComponent( 6045 );
			AddComponent( ac, 7, -1, 0 );
			ac = new AddonComponent( 3204 );
			AddComponent( ac, 8, -1, 0 );
			ac = new AddonComponent( 13567 );
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 3212 );
			AddComponent( ac, 6, -2, 0 );
			ac = new AddonComponent( 6045 );
			AddComponent( ac, 6, -2, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 5, 0, 0 );
			ac = new AddonComponent( 3333 );
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 3518 );
			AddComponent( ac, 7, 0, 0 );
			ac = new AddonComponent( 3518 );
			AddComponent( ac, 5, -1, 0 );
			ac = new AddonComponent( 6045 );
			AddComponent( ac, -4, -1, 0 );
			ac = new AddonComponent( 3332 );
			AddComponent( ac, 7, -1, 0 );
			ac = new AddonComponent( 6045 );
			AddComponent( ac, -4, -1, 0 );
			ac = new AddonComponent( 3332 );
			AddComponent( ac, 0, -2, 0 );
			ac = new AddonComponent( 6040 );
			AddComponent( ac, 3, -1, 0 );
			ac = new AddonComponent( 13578 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 3209 );
			AddComponent( ac, -2, -2, 0 );
			ac = new AddonComponent( 3208 );
			AddComponent( ac, 1, -2, 2 );
			ac = new AddonComponent( 6040 );
			AddComponent( ac, 3, 0, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 7, 0, 0 );
			ac = new AddonComponent( 6045 );
			AddComponent( ac, -4, 0, 0 );
			ac = new AddonComponent( 6045 );
			AddComponent( ac, 8, 0, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, -4, -1, 5 );
			ac = new AddonComponent( 6047 );
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 3223 );
			AddComponent( ac, -5, 0, 5 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, -2, -1, 0 );
			ac = new AddonComponent( 3333 );
			AddComponent( ac, 3, -2, 0 );
			ac = new AddonComponent( 636 );
			AddComponent( ac, -5, -1, 0 );
			ac = new AddonComponent( 631 );
			AddComponent( ac, -4, -2, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, -2, 0, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, -3, 0, 0 );
			ac = new AddonComponent( 3204 );
			AddComponent( ac, 0, -3, 0 );
			ac = new AddonComponent( 3149 );
			AddComponent( ac, 8, -2, 0 );
			ac = new AddonComponent( 3212 );
			AddComponent( ac, 2, -3, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, -2, 1, 0 );
			ac = new AddonComponent( 3209 );
			AddComponent( ac, 6, 4, 0 );
			ac = new AddonComponent( 3204 );
			AddComponent( ac, -4, 3, 0 );
			ac = new AddonComponent( 13567 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, -4, 1, 5 );
			ac = new AddonComponent( 13573 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 6049 );
			AddComponent( ac, 0, 2, 0 );
			ac = new AddonComponent( 6049 );
			AddComponent( ac, -2, 2, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 5, 2, 0 );
			ac = new AddonComponent( 6045 );
			AddComponent( ac, 6, 2, 0 );
			ac = new AddonComponent( 13446 );
			AddComponent( ac, -4, 1, 0 );
			ac = new AddonComponent( 8129 );
			AddComponent( ac, 4, 2, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 6, 1, 0 );
			ac = new AddonComponent( 3212 );
			AddComponent( ac, -3, 2, 0 );
			ac = new AddonComponent( 3149 );
			AddComponent( ac, -5, 3, 0 );
			ac = new AddonComponent( 6050 );
			AddComponent( ac, -1, 2, 0 );
			ac = new AddonComponent( 3149 );
			AddComponent( ac, -1, 3, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 5, 1, 0 );
			ac = new AddonComponent( 3208 );
			AddComponent( ac, 5, 4, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 4, 2, 0 );
			ac = new AddonComponent( 3333 );
			AddComponent( ac, -2, 2, 0 );
			ac = new AddonComponent( 6050 );
			AddComponent( ac, 1, 2, 0 );
			ac = new AddonComponent( 6059 );
			AddComponent( ac, 2, 2, 0 );
			ac = new AddonComponent( 7038 );
			AddComponent( ac, -4, 2, 0 );
			ac = new AddonComponent( 3149 );
			AddComponent( ac, 1, 4, 0 );
			ac = new AddonComponent( 6040 );
			AddComponent( ac, 3, 1, 0 );
			ac = new AddonComponent( 3208 );
			AddComponent( ac, -1, 2, 0 );
			ac = new AddonComponent( 3208 );
			AddComponent( ac, 2, 3, 0 );
			ac = new AddonComponent( 3206 );
			AddComponent( ac, 7, 2, 0 );
			ac = new AddonComponent( 3521 );
			ac.Hue = 1150;
			AddComponent( ac, 2, 2, 0 );
			ac = new AddonComponent( 13446 );
			AddComponent( ac, 3, 2, 0 );
			ac = new AddonComponent( 3209 );
			AddComponent( ac, 0, 4, 0 );
			ac = new AddonComponent( 3149 );
			AddComponent( ac, 7, 3, 0 );
			ac = new AddonComponent( 8131 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 6045 );
			AddComponent( ac, 5, 3, 0 );
			ac = new AddonComponent( 8753 );
			AddComponent( ac, 3, 4, 0 );
			ac = new AddonComponent( 8750 );
			AddComponent( ac, -2, 3, 0 );
			ac = new AddonComponent( 3204 );
			AddComponent( ac, 4, 4, 0 );
			ac = new AddonComponent( 3333 );
			AddComponent( ac, 5, 3, 0 );
			ac = new AddonComponent( 3333 );
			AddComponent( ac, 7, 1, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 4, 1, 0 );
			ac = new AddonComponent( 13555 );
			AddComponent( ac, -2, 1, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, -4, 1, 0 );
			ac = new AddonComponent( 631 );
			AddComponent( ac, -4, 1, 0 );
			ac = new AddonComponent( 6049 );
			AddComponent( ac, 3, 3, 0 );
			ac = new AddonComponent( 6064 );
			AddComponent( ac, 4, 4, 0 );
			ac = new AddonComponent( 6055 );
			AddComponent( ac, 5, 4, 0 );
			ac = new AddonComponent( 6064 );
			AddComponent( ac, 2, 3, 0 );
			ac = new AddonComponent( 3333 );
			AddComponent( ac, 1, 2, 0 );
			ac = new AddonComponent( 6055 );
			AddComponent( ac, 7, 2, 0 );
			ac = new AddonComponent( 3204 );
			AddComponent( ac, 0, 3, 0 );
			ac = new AddonComponent( 6055 );
			AddComponent( ac, 6, 3, 0 );
			ac = new AddonComponent( 3332 );
			AddComponent( ac, 6, 3, 0 );
			ac = new AddonComponent( 3518 );
			AddComponent( ac, 2, 2, 0 );
			ac = new AddonComponent( 7038 );
			AddComponent( ac, -5, 2, 0 );
			ac = new AddonComponent( 632 );
			AddComponent( ac, -3, 1, 0 );
			ac = new AddonComponent( 6045 );
			AddComponent( ac, 7, 1, 0 );
			ac = new AddonComponent( 3518 );
			AddComponent( ac, 6, 1, 0 );
			ac = new AddonComponent( 3259 );
			AddComponent( ac, 2, 4, 0 );
			ac = new AddonComponent( 636 );
			AddComponent( ac, -5, 1, 0 );
			ac = new AddonComponent( 3211 );
			AddComponent( ac, 6, 2, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 3, 2, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, -3, 1, 0 );
			ac = new AddonComponent( 3332 );
			AddComponent( ac, 4, 3, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 3332 );
			AddComponent( ac, 6, 2, 0 );
			ac = new AddonComponent( 6059 );
			AddComponent( ac, 4, 3, 0 );
			ac = new AddonComponent( 6055 );
			AddComponent( ac, 8, 1, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 3206 );
			AddComponent( ac, 1, 3, 0 );

		}

		public AG_17x9brookeastAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class AG_17x9brookeastAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new AG_17x9brookeastAddon();
			}
		}

		[Constructable]
		public AG_17x9brookeastAddonDeed()
		{
			Name = "AG_17x9brookeast";
		}

		public AG_17x9brookeastAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}