/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class AG_1x4fireplacesouthAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new AG_1x4fireplacesouthAddonDeed();
			}
		}

		[ Constructable ]
		public AG_1x4fireplacesouthAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 13897 );
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 13843 );
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 13849 );
			AddComponent( ac, -2, -1, 0 );
			ac = new AddonComponent( 13897 );
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 703 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 13843 );
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 4850 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 9225 );
			AddComponent( ac, 1, 1, 2 );
			ac = new AddonComponent( 704 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 13897 );
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 13897 );
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 4850 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 13896 );
			AddComponent( ac, -2, 0, 0 );
			ac = new AddonComponent( 4850 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 4850 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 6571 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 0, 0, 2 );

		}

		public AG_1x4fireplacesouthAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class AG_1x4fireplacesouthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new AG_1x4fireplacesouthAddon();
			}
		}

		[Constructable]
		public AG_1x4fireplacesouthAddonDeed()
		{
			Name = "AG_1x4fireplacesouth";
		}

		public AG_1x4fireplacesouthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}