/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class AG_5x3lilyplanterAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new AG_5x3lilyplanterAddonDeed();
			}
		}

		[ Constructable ]
		public AG_5x3lilyplanterAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 2818 );
			ac.Name = "Planter";
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 3223 );
			AddComponent( ac, -1, 0, 3 );
			ac = new AddonComponent( 3241 );
			AddComponent( ac, -1, 0, 7 );
			ac = new AddonComponent( 3205 );
			AddComponent( ac, -1, 0, 5 );
			ac = new AddonComponent( 2817 );
			ac.Name = "Planter";
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 2816 );
			ac.Name = "Planter";
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 3212 );
			ac.Hue = 1150;
			AddComponent( ac, 1, 0, 4 );
			ac = new AddonComponent( 3211 );
			ac.Hue = 1150;
			AddComponent( ac, 1, 0, 5 );
			ac = new AddonComponent( 9037 );
			AddComponent( ac, 1, 0, 5 );
			ac = new AddonComponent( 6811 );
			AddComponent( ac, 0, 0, 11 );
			ac = new AddonComponent( 3265 );
			AddComponent( ac, 0, 0, 7 );

		}

		public AG_5x3lilyplanterAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class AG_5x3lilyplanterAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new AG_5x3lilyplanterAddon();
			}
		}

		[Constructable]
		public AG_5x3lilyplanterAddonDeed()
		{
			Name = "AG_5x3lilyplanter";
		}

		public AG_5x3lilyplanterAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}