/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class AG_7x7stardecorAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new AG_7x7stardecorAddonDeed();
			}
		}

		[ Constructable ]
		public AG_7x7stardecorAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 6378 );
			AddComponent( ac, 3, -1, 2 );
			ac = new AddonComponent( 4440 );
			AddComponent( ac, 3, 1, 2 );
			ac = new AddonComponent( 6378 );
			AddComponent( ac, -1, 3, 2 );
			ac = new AddonComponent( 4435 );
			AddComponent( ac, 0, 3, 7 );
			ac = new AddonComponent( 6378 );
			AddComponent( ac, 3, 3, 4 );
			ac = new AddonComponent( 4435 );
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 4440 );
			AddComponent( ac, 0, 2, 0 );
			ac = new AddonComponent( 3212 );
			ac.Hue = 1150;
			AddComponent( ac, 3, -1, 2 );
			ac = new AddonComponent( 3211 );
			ac.Hue = 1150;
			AddComponent( ac, -1, 3, 2 );
			ac = new AddonComponent( 6811 );
			AddComponent( ac, 3, -2, 2 );
			ac = new AddonComponent( 6811 );
			AddComponent( ac, -2, 3, 2 );
			ac = new AddonComponent( 3223 );
			AddComponent( ac, 3, 3, 2 );
			ac = new AddonComponent( 9037 );
			AddComponent( ac, 2, 3, 0 );
			ac = new AddonComponent( 9037 );
			AddComponent( ac, 3, 1, 2 );
			ac = new AddonComponent( 9037 );
			AddComponent( ac, 1, 3, 2 );
			ac = new AddonComponent( 3223 );
			AddComponent( ac, 3, 0, 2 );
			ac = new AddonComponent( 3223 );
			AddComponent( ac, 0, 3, 2 );
			ac = new AddonComponent( 8515 );
			AddComponent( ac, 3, 1, 0 );
			ac = new AddonComponent( 8516 );
			AddComponent( ac, 3, 0, 0 );
			ac = new AddonComponent( 8515 );
			AddComponent( ac, 3, -1, 0 );
			ac = new AddonComponent( 8514 );
			AddComponent( ac, 3, -2, 0 );
			ac = new AddonComponent( 8511 );
			AddComponent( ac, 0, 3, 0 );
			ac = new AddonComponent( 8516 );
			AddComponent( ac, -1, 3, 0 );
			ac = new AddonComponent( 8515 );
			AddComponent( ac, -2, 3, 0 );
			ac = new AddonComponent( 8512 );
			AddComponent( ac, 1, 3, 0 );
			ac = new AddonComponent( 9036 );
			AddComponent( ac, 2, 2, 0 );
			ac = new AddonComponent( 9035 );
			AddComponent( ac, 2, 3, 9 );
			ac = new AddonComponent( 9035 );
			AddComponent( ac, 2, 3, 16 );
			ac = new AddonComponent( 3212 );
			ac.Hue = 1150;
			AddComponent( ac, 3, 1, 2 );
			ac = new AddonComponent( 9035 );
			AddComponent( ac, 3, 2, 9 );
			ac = new AddonComponent( 3211 );
			ac.Hue = 1150;
			AddComponent( ac, 1, 3, 2 );
			ac = new AddonComponent( 9035 );
			AddComponent( ac, 3, 2, 15 );
			ac = new AddonComponent( 9037 );
			AddComponent( ac, 0, 3, 0 );
			ac = new AddonComponent( 8513 );
			AddComponent( ac, 3, 3, 0 );
			ac = new AddonComponent( 9037 );
			AddComponent( ac, 3, 2, 0 );
			ac = new AddonComponent( 9037 );
			AddComponent( ac, 2, 3, 0 );
			ac = new AddonComponent( 13920 );
			AddComponent( ac, -1, -1, 2 );
			ac = new AddonComponent( 4824 );
			ac.Hue = 1150;
			AddComponent( ac, 2, 3, 0 );
			ac = new AddonComponent( 8513 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 8512 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 8516 );
			AddComponent( ac, -2, 1, 0 );
			ac = new AddonComponent( 8515 );
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 8514 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 8513 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 8512 );
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 8511 );
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 8515 );
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 8516 );
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 8515 );
			AddComponent( ac, -2, 0, 0 );
			ac = new AddonComponent( 8516 );
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 8514 );
			AddComponent( ac, -2, -1, 0 );
			ac = new AddonComponent( 8513 );
			AddComponent( ac, 2, -2, 0 );
			ac = new AddonComponent( 8511 );
			AddComponent( ac, 0, -2, 0 );
			ac = new AddonComponent( 8512 );
			AddComponent( ac, 1, -2, 0 );
			ac = new AddonComponent( 8515 );
			AddComponent( ac, 2, 2, 0 );
			ac = new AddonComponent( 8514 );
			AddComponent( ac, 1, 2, 0 );
			ac = new AddonComponent( 4825 );
			ac.Hue = 1150;
			AddComponent( ac, 3, 2, 0 );
			ac = new AddonComponent( 9037 );
			AddComponent( ac, 3, 0, 2 );
			ac = new AddonComponent( 8512 );
			AddComponent( ac, -1, 2, 0 );
			ac = new AddonComponent( 8515 );
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 8511 );
			AddComponent( ac, -1, -2, 0 );
			ac = new AddonComponent( 8516 );
			AddComponent( ac, -2, -2, 0 );
			ac = new AddonComponent( 8511 );
			AddComponent( ac, -2, 2, 0 );
			ac = new AddonComponent( 8513 );
			AddComponent( ac, 0, 2, 0 );
			ac = new AddonComponent( 8514 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 4967 );
			AddComponent( ac, 3, 3, 1 );

		}

		public AG_7x7stardecorAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class AG_7x7stardecorAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new AG_7x7stardecorAddon();
			}
		}

		[Constructable]
		public AG_7x7stardecorAddonDeed()
		{
			Name = "AG_7x7stardecor";
		}

		public AG_7x7stardecorAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}