/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class AG_windowboxsouth2Addon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new AG_windowboxsouth2AddonDeed();
			}
		}

		[ Constructable ]
		public AG_windowboxsouth2Addon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 2826 );
			ac.Name = "window box";
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 3241 );
			AddComponent( ac, 0, 0, 10 );
			ac = new AddonComponent( 3208 );
			AddComponent( ac, 0, 0, 6 );
			ac = new AddonComponent( 3209 );
			AddComponent( ac, 0, 0, 4 );
			ac = new AddonComponent( 3152 );
			AddComponent( ac, 0, 0, 4 );

		}

		public AG_windowboxsouth2Addon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class AG_windowboxsouth2AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new AG_windowboxsouth2Addon();
			}
		}

		[Constructable]
		public AG_windowboxsouth2AddonDeed()
		{
			Name = "AG_windowboxsouth2";
		}

		public AG_windowboxsouth2AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}