
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class StygianDragonAltarAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {1801, 0, -1, 0}, {1801, 1, -1, 0}, {1801, -1, 1, 0}// 3	4	5	
			, {1801, -1, 0, 0}, {1801, 0, 1, 0}, {1801, 1, 1, 0}// 8	10	11	
			, {1801, 0, 0, 0}, {1803, 1, 0, 0}, {1801, -1, -1, 0}// 13	14	16	
			, {8402, 0, 0, 5}// 17	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new StygianDragonAltarAddonDeed();
			}
		}

		[ Constructable ]
		public StygianDragonAltarAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 6587, 1, -1, 7, 2416, 1, "", 1);// 1
			AddComplexComponent( (BaseAddon) this, 6587, -1, -1, 5, 2416, 1, "", 1);// 2
			AddComplexComponent( (BaseAddon) this, 6587, -1, 1, 7, 2416, 1, "", 1);// 6
			AddComplexComponent( (BaseAddon) this, 6587, 1, 1, 7, 2416, 1, "", 1);// 7
			AddComplexComponent( (BaseAddon) this, 7885, 0, -1, 6, 0, 1, "", 1);// 9
			AddComplexComponent( (BaseAddon) this, 7885, 0, 1, 7, 0, 1, "", 1);// 12
			AddComplexComponent( (BaseAddon) this, 7885, -1, 0, 7, 0, 1, "", 1);// 15

		}

		public StygianDragonAltarAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class StygianDragonAltarAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new StygianDragonAltarAddon();
			}
		}

		[Constructable]
		public StygianDragonAltarAddonDeed()
		{
			Name = "StygianDragonAltar";
		}

		public StygianDragonAltarAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}