/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class AG_bloodskullstatueeastAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new AG_bloodskullstatueeastAddonDeed();
			}
		}

		[ Constructable ]
		public AG_bloodskullstatueeastAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 6926 );
			AddComponent( ac, 2, 0, 1 );
			ac = new AddonComponent( 7385 );
			AddComponent( ac, 1, -1, 1 );
			ac = new AddonComponent( 4652 );
			AddComponent( ac, -2, -2, 1 );
			ac = new AddonComponent( 7385 );
			AddComponent( ac, -1, 0, 1 );
			ac = new AddonComponent( 7385 );
			AddComponent( ac, 0, -1, 1 );
			ac = new AddonComponent( 7385 );
			AddComponent( ac, 2, 0, 1 );
			ac = new AddonComponent( 7385 );
			AddComponent( ac, -1, 1, 1 );
			ac = new AddonComponent( 4654 );
			AddComponent( ac, -3, -1, 1 );
			ac = new AddonComponent( 7385 );
			AddComponent( ac, 2, -1, 1 );
			ac = new AddonComponent( 4653 );
			AddComponent( ac, 1, -2, 1 );
			ac = new AddonComponent( 7369 );
			AddComponent( ac, -3, 0, 1 );
			ac = new AddonComponent( 5701 );
			AddComponent( ac, -3, -2, 1 );
			ac = new AddonComponent( 7385 );
			AddComponent( ac, 3, 1, 1 );
			ac = new AddonComponent( 7369 );
			AddComponent( ac, -2, -1, 1 );
			ac = new AddonComponent( 7372 );
			AddComponent( ac, 2, -2, 1 );
			ac = new AddonComponent( 7375 );
			AddComponent( ac, -4, 0, 1 );
			ac = new AddonComponent( 6872 );
			AddComponent( ac, 3, 1, 1 );
			ac = new AddonComponent( 4650 );
			AddComponent( ac, -2, -1, 1 );
			ac = new AddonComponent( 12401 );
			ac.Hue = 1150;
			AddComponent( ac, 1, 0, 1 );
			ac = new AddonComponent( 3786 );
			AddComponent( ac, 0, -2, 1 );
			ac = new AddonComponent( 7385 );
			AddComponent( ac, 1, 0, 1 );
			ac = new AddonComponent( 7385 );
			AddComponent( ac, -3, 1, 1 );
			ac = new AddonComponent( 7378 );
			AddComponent( ac, -4, 1, 1 );
			ac = new AddonComponent( 6875 );
			AddComponent( ac, -1, 1, 1 );
			ac = new AddonComponent( 7385 );
			AddComponent( ac, -2, 1, 1 );
			ac = new AddonComponent( 7385 );
			AddComponent( ac, 3, 0, 1 );
			ac = new AddonComponent( 6875 );
			AddComponent( ac, 2, 1, 1 );
			ac = new AddonComponent( 7381 );
			AddComponent( ac, 1, -2, 1 );
			ac = new AddonComponent( 7385 );
			AddComponent( ac, 1, 1, 1 );
			ac = new AddonComponent( 7385 );
			AddComponent( ac, 2, 1, 1 );
			ac = new AddonComponent( 4650 );
			AddComponent( ac, 0, -2, 1 );
			ac = new AddonComponent( 7385 );
			AddComponent( ac, 0, 1, 1 );
			ac = new AddonComponent( 4653 );
			AddComponent( ac, 3, -1, 1 );
			ac = new AddonComponent( 7369 );
			AddComponent( ac, -1, -2, 1 );
			ac = new AddonComponent( 4652 );
			AddComponent( ac, -3, -2, 1 );
			ac = new AddonComponent( 8700 );
			AddComponent( ac, -3, 1, 0 );
			ac = new AddonComponent( 7372 );
			AddComponent( ac, 3, -1, 1 );
			ac = new AddonComponent( 7385 );
			AddComponent( ac, -2, 0, 1 );
			ac = new AddonComponent( 7385 );
			AddComponent( ac, 0, 0, 1 );
			ac = new AddonComponent( 7385 );
			AddComponent( ac, -1, -1, 1 );
			ac = new AddonComponent( 7382 );
			AddComponent( ac, 0, -2, 1 );
			ac = new AddonComponent( 12400 );
			ac.Hue = 1150;
			AddComponent( ac, 0, 1, 1 );
			ac = new AddonComponent( 12399 );
			ac.Hue = 1150;
			AddComponent( ac, 1, 1, 1 );
			ac = new AddonComponent( 3814 );
			AddComponent( ac, 1, 0, 1 );
			ac = new AddonComponent( 5701 );
			AddComponent( ac, -1, -3, 1 );
			ac = new AddonComponent( 7383 );
			AddComponent( ac, 4, 1, 1 );
			ac = new AddonComponent( 4454 );
			AddComponent( ac, 1, -1, 1 );
			ac = new AddonComponent( 6926 );
			AddComponent( ac, 2, -1, 1 );
			ac = new AddonComponent( 7385 );
			AddComponent( ac, -2, 2, 1 );
			ac = new AddonComponent( 7385 );
			AddComponent( ac, 2, 2, 1 );
			ac = new AddonComponent( 7385 );
			AddComponent( ac, 2, 3, 1 );
			ac = new AddonComponent( 6927 );
			AddComponent( ac, 2, 3, 1 );
			ac = new AddonComponent( 7377 );
			AddComponent( ac, -4, 2, 1 );
			ac = new AddonComponent( 3811 );
			AddComponent( ac, -2, 3, 1 );
			ac = new AddonComponent( 7385 );
			AddComponent( ac, 1, 2, 1 );
			ac = new AddonComponent( 6873 );
			AddComponent( ac, 2, 2, 1 );
			ac = new AddonComponent( 3812 );
			AddComponent( ac, -2, 4, 1 );
			ac = new AddonComponent( 4651 );
			AddComponent( ac, -1, 4, 1 );
			ac = new AddonComponent( 7385 );
			AddComponent( ac, -1, 3, 1 );
			ac = new AddonComponent( 6873 );
			AddComponent( ac, -1, 2, 1 );
			ac = new AddonComponent( 7385 );
			AddComponent( ac, -3, 2, 1 );
			ac = new AddonComponent( 7385 );
			AddComponent( ac, 0, 3, 1 );
			ac = new AddonComponent( 7371 );
			AddComponent( ac, -1, 4, 1 );
			ac = new AddonComponent( 7385 );
			AddComponent( ac, -2, 3, 1 );
			ac = new AddonComponent( 7380 );
			AddComponent( ac, 0, 4, 1 );
			ac = new AddonComponent( 7385 );
			AddComponent( ac, -1, 2, 1 );
			ac = new AddonComponent( 6876 );
			AddComponent( ac, 0, 2, 1 );
			ac = new AddonComponent( 6872 );
			AddComponent( ac, 3, 2, 1 );
			ac = new AddonComponent( 3811 );
			AddComponent( ac, -1, 4, 1 );
			ac = new AddonComponent( 7370 );
			AddComponent( ac, -3, 3, 1 );
			ac = new AddonComponent( 7371 );
			AddComponent( ac, 3, 3, 1 );
			ac = new AddonComponent( 6922 );
			AddComponent( ac, 0, 3, 1 );
			ac = new AddonComponent( 7370 );
			AddComponent( ac, -2, 4, 1 );
			ac = new AddonComponent( 7385 );
			AddComponent( ac, 0, 2, 1 );
			ac = new AddonComponent( 7379 );
			AddComponent( ac, 1, 4, 1 );
			ac = new AddonComponent( 7385 );
			AddComponent( ac, 3, 2, 1 );
			ac = new AddonComponent( 7384 );
			AddComponent( ac, 4, 2, 1 );
			ac = new AddonComponent( 6876 );
			AddComponent( ac, 1, 2, 1 );
			ac = new AddonComponent( 8708 );
			AddComponent( ac, -1, 3, 2 );
			ac = new AddonComponent( 7380 );
			AddComponent( ac, 2, 4, 1 );
			ac = new AddonComponent( 7385 );
			AddComponent( ac, 1, 3, 1 );

		}

		public AG_bloodskullstatueeastAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class AG_bloodskullstatueeastAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new AG_bloodskullstatueeastAddon();
			}
		}

		[Constructable]
		public AG_bloodskullstatueeastAddonDeed()
		{
			Name = "AG_bloodskullstatueeast";
		}

		public AG_bloodskullstatueeastAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}