/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class AG_colorfulrosevaseAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new AG_colorfulrosevaseAddonDeed();
			}
		}

		[ Constructable ]
		public AG_colorfulrosevaseAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 3151 );
			AddComponent( ac, 1, 1, 23 );
			ac = new AddonComponent( 3235 );
			AddComponent( ac, 0, 0, 16 );
			ac = new AddonComponent( 2887 );
			ac.Hue = 1150;
			AddComponent( ac, 0, 0, 14 );
			ac = new AddonComponent( 3152 );
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 3152 );
			AddComponent( ac, 0, 0, 14 );
			ac = new AddonComponent( 3151 );
			AddComponent( ac, 0, 0, 14 );
			ac = new AddonComponent( 6378 );
			ac.Name = "Whispering Rose";
			AddComponent( ac, 0, 0, 26 );

		}

		public AG_colorfulrosevaseAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class AG_colorfulrosevaseAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new AG_colorfulrosevaseAddon();
			}
		}

		[Constructable]
		public AG_colorfulrosevaseAddonDeed()
		{
			Name = "AG_colorfulrosevase";
		}

		public AG_colorfulrosevaseAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}