/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class AG_PlanterSouthAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new AG_PlanterSouthAddonDeed();
			}
		}

		[ Constructable ]
		public AG_PlanterSouthAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 6811 );
			AddComponent( ac, 1, 0, 3 );
			ac = new AddonComponent( 3204 );
			AddComponent( ac, 1, 0, 7 );
			ac = new AddonComponent( 3206 );
			AddComponent( ac, 1, 1, 11 );
			ac = new AddonComponent( 3376 );
			AddComponent( ac, 1, 0, 3 );
			ac = new AddonComponent( 3205 );
			AddComponent( ac, 0, 1, 9 );
			ac = new AddonComponent( 3224 );
			AddComponent( ac, 0, 0, 2 );
			ac = new AddonComponent( 3223 );
			AddComponent( ac, -1, 0, 4 );
			ac = new AddonComponent( 2817 );
			ac.Name = "Planter";
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 2816 );
			ac.Name = "Planter";
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 2818 );
			ac.Name = "Planter";
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 3205 );
			AddComponent( ac, -1, 0, 3 );

		}

		public AG_PlanterSouthAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class AG_PlanterSouthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new AG_PlanterSouthAddon();
			}
		}

		[Constructable]
		public AG_PlanterSouthAddonDeed()
		{
			Name = "AG_PlanterSouth";
		}

		public AG_PlanterSouthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}