/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class AG_santasliegheastAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new AG_santasliegheastAddonDeed();
			}
		}

		[ Constructable ]
		public AG_santasliegheastAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 3272 );
			AddComponent( ac, -4, -1, 0 );
			ac = new AddonComponent( 6088 );
			AddComponent( ac, -5, 2, 0 );
			ac = new AddonComponent( 6091 );
			AddComponent( ac, -3, -2, 0 );
			ac = new AddonComponent( 14990 );
			AddComponent( ac, -5, 1, 0 );
			ac = new AddonComponent( 6085 );
			AddComponent( ac, -6, -2, 0 );
			ac = new AddonComponent( 6077 );
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 6078 );
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 6078 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 6078 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 6078 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 6089 );
			AddComponent( ac, -2, 2, 0 );
			ac = new AddonComponent( 6082 );
			AddComponent( ac, -5, 1, 0 );
			ac = new AddonComponent( 6077 );
			AddComponent( ac, -3, 0, 0 );
			ac = new AddonComponent( 6091 );
			AddComponent( ac, -5, -2, 0 );
			ac = new AddonComponent( 6077 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 14949 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 6091 );
			AddComponent( ac, 2, -2, 0 );
			ac = new AddonComponent( 6091 );
			AddComponent( ac, 1, -2, 0 );
			ac = new AddonComponent( 6077 );
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 6077 );
			AddComponent( ac, -5, -1, 0 );
			ac = new AddonComponent( 6091 );
			AddComponent( ac, -1, -2, 0 );
			ac = new AddonComponent( 6078 );
			AddComponent( ac, -4, 1, 0 );
			ac = new AddonComponent( 6090 );
			AddComponent( ac, -6, 0, 0 );
			ac = new AddonComponent( 6077 );
			AddComponent( ac, -4, -1, 0 );
			ac = new AddonComponent( 6091 );
			AddComponent( ac, 0, -2, 0 );
			ac = new AddonComponent( 6077 );
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 6088 );
			AddComponent( ac, -6, 1, 0 );
			ac = new AddonComponent( 14962 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 6091 );
			AddComponent( ac, -4, -2, 0 );
			ac = new AddonComponent( 6089 );
			AddComponent( ac, -4, 2, 0 );
			ac = new AddonComponent( 6089 );
			AddComponent( ac, -1, 2, 0 );
			ac = new AddonComponent( 6077 );
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 6089 );
			AddComponent( ac, 0, 2, 0 );
			ac = new AddonComponent( 6077 );
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 6077 );
			AddComponent( ac, -2, -1, 0 );
			ac = new AddonComponent( 6077 );
			AddComponent( ac, -5, 0, 0 );
			ac = new AddonComponent( 6090 );
			AddComponent( ac, -6, -1, 0 );
			ac = new AddonComponent( 6078 );
			AddComponent( ac, -3, 1, 0 );
			ac = new AddonComponent( 14934 );
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 6077 );
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 14962 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 6077 );
			AddComponent( ac, -4, 0, 0 );
			ac = new AddonComponent( 6077 );
			AddComponent( ac, -3, -1, 0 );
			ac = new AddonComponent( 6089 );
			AddComponent( ac, 1, 2, 0 );
			ac = new AddonComponent( 14934 );
			AddComponent( ac, -2, 1, 0 );
			ac = new AddonComponent( 6078 );
			AddComponent( ac, -2, 1, 0 );
			ac = new AddonComponent( 6091 );
			AddComponent( ac, -2, -2, 0 );
			ac = new AddonComponent( 14989 );
			AddComponent( ac, -4, 1, 0 );
			ac = new AddonComponent( 6089 );
			AddComponent( ac, 2, 2, 0 );
			ac = new AddonComponent( 6077 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 6077 );
			AddComponent( ac, -2, 0, 0 );
			ac = new AddonComponent( 6089 );
			AddComponent( ac, -3, 2, 0 );
			ac = new AddonComponent( 6077 );
			AddComponent( ac, 4, -1, 0 );
			ac = new AddonComponent( 6078 );
			AddComponent( ac, 4, 1, 0 );
			ac = new AddonComponent( 6081 );
			AddComponent( ac, 5, 1, 0 );
			ac = new AddonComponent( 6077 );
			AddComponent( ac, 5, -1, 0 );
			ac = new AddonComponent( 6077 );
			AddComponent( ac, 3, 0, 0 );
			ac = new AddonComponent( 6092 );
			AddComponent( ac, 6, -1, 0 );
			ac = new AddonComponent( 6092 );
			AddComponent( ac, 6, 0, 0 );
			ac = new AddonComponent( 6091 );
			AddComponent( ac, 3, -2, 0 );
			ac = new AddonComponent( 6086 );
			AddComponent( ac, 6, -2, 0 );
			ac = new AddonComponent( 14934 );
			AddComponent( ac, 4, 1, 0 );
			ac = new AddonComponent( 6077 );
			AddComponent( ac, 4, 0, 0 );
			ac = new AddonComponent( 6089 );
			AddComponent( ac, 3, 2, 0 );
			ac = new AddonComponent( 6087 );
			AddComponent( ac, 5, 2, 0 );
			ac = new AddonComponent( 14962 );
			AddComponent( ac, 3, 1, 0 );
			ac = new AddonComponent( 6091 );
			AddComponent( ac, 4, -2, 0 );
			ac = new AddonComponent( 14962 );
			AddComponent( ac, 5, 1, 0 );
			ac = new AddonComponent( 6091 );
			AddComponent( ac, 5, -2, 0 );
			ac = new AddonComponent( 6077 );
			AddComponent( ac, 3, -1, 0 );
			ac = new AddonComponent( 14961 );
			AddComponent( ac, 6, 0, 0 );
			ac = new AddonComponent( 6078 );
			AddComponent( ac, 3, 1, 0 );
			ac = new AddonComponent( 6077 );
			AddComponent( ac, 5, 0, 0 );
			ac = new AddonComponent( 6087 );
			AddComponent( ac, 6, 1, 0 );
			ac = new AddonComponent( 6089 );
			AddComponent( ac, 4, 2, 0 );

		}

		public AG_santasliegheastAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class AG_santasliegheastAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new AG_santasliegheastAddon();
			}
		}

		[Constructable]
		public AG_santasliegheastAddonDeed()
		{
			Name = "AG_santasliegheast";
		}

		public AG_santasliegheastAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}