/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class AG_tablevaserosesAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new AG_tablevaserosesAddonDeed();
			}
		}

		[ Constructable ]
		public AG_tablevaserosesAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 6378 );
			ac.Name = "Whispering Rose";
			AddComponent( ac, 1, 1, 17 );
			ac = new AddonComponent( 3153 );
			AddComponent( ac, 0, 0, 8 );
			ac = new AddonComponent( 2886 );
			ac.Hue = 1150;
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 6378 );
			ac.Name = "Whispering Rose";
			AddComponent( ac, 1, 1, 14 );

		}

		public AG_tablevaserosesAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class AG_tablevaserosesAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new AG_tablevaserosesAddon();
			}
		}

		[Constructable]
		public AG_tablevaserosesAddonDeed()
		{
			Name = "AG_tablevaseroses";
		}

		public AG_tablevaserosesAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}